% This routine constitutes an 'e-mail' register of people interested in SPM
% and automatically mails the ASCII file spm_UPDATE to all people on the
% register
%---------------------------------------------------------------------------
% %W% SPM %E%

P = [
'sekim@smc.samsung.co.kr                     ';		% (Sang Eun Kim)
'demonet@janus223.purpan.inserm.fr           ';		% (JeanFrancois Demonet)
'd.c.barber@sheffield.ac.uk                  ';		% (David Barber)
'tuna@alw.nih.gov                            ';		% (Tom Herman)
'd.porter@ich.bpmf.ac.uk                     ';		% (Alan Connelly)
'jbreier@oto1.med.uth.tmc.edu                ';		% (Josh Breier)
'enda@pet.tmig.or.jp                         ';		% (Michio Send)
'weber@ikra.med.uni-muenchen.de              ';		% (Juergen Weber)
'eturner@Box-e.nih.gov                       ';		% (Erick H. Turner)
'cyrill@nuklearmed.unizh.ch                  ';		% (Cyrill Burger)
'paul@nuclear-medicine.ucl.ac.uk             ';		% (Paul Acton)
'reutter@imasun.lbl.gov                      ';		% (Bryan Reutter)
'rbaum@rs6000.mri.akh-wien.ac.at             ';		% (Richard Baumgartner)
'ip5@columbia.edu                            ';		% (Isak Prohovnik)
'jiang@trionix.com                           ';		% (Jennifer Jiang)
'wbrown@facstaff.wisc.edu                    ';		% (Doug Brown)
'huckinss@vax.cs.hscsyr.edu                  ';		% 
'jaggi@cvrc.med.upenn.edu                    ';		% (Jurg Jaggi)
'blin@topo.ucl.ac.be                         ';		% (Jerome Blin)
'otto@pet.wayne.edu                          ';		% (Otto Muzik)
'yrg@vuse.vanderbilt.edu                     ';		% (Yaorong Ge)
'bidaut@cih.hcuge.ch                         ';		% (Luc Bidaut)
'med042@aix.sp.kfa-juelich.de                ';		% (Stefan Posse)
'b.jones@cxwms.ac.uk                         ';		% (Barbara Jones)
'heeger@white.stanford.edu                   ';		% (David Heeger)
'p.jarritt@nucmed.ucl.ac.uk                  ';		% (Peter Jarritt)
'karl@cu.rpms.ac.uk                          ';		% (Karl Friston)
'artlai@utu.fi                               ';		% (Arto Laihinen)
'liqun@nmr.ion.bpmf.ac.uk                    ';		% (Liqun Wang)
'tallent@nmrsun.ncrr.nih.gov                 ';		% ((Kathleen Tallent)
'santha@nmrsun.ncrr.nih.gov                  ';		%
'horwitz@alw.nih.gov                         ';		% (Barry Horwitz)
'swarach@mercury.bih.harvard.edu             ';		% (Steven Warach)
'schwabe@mr.uni-duesseldorf.de               ';		% (Birgit Schwabe)
'robert@doug.med.utah.eduu                   ';  	% (Robert Burr)
'jiang@nmr.mgh.harvard.edu                   ';  	% (Aiping Jiang)
'74740.410@compuserve.com                    ';  	% (Joel Steinberg)
'Andrew.J.Saykin@dartmouth.edu               ';  	% (Andrew Saykin)
'dsilverman@v401.nuc.ucla.edu                ';  	% (Dan Silverman)
'rwcox@post.its.mcw.edu                      ';  	% (Robert Cox)
'liddle@unixg.ubc.ca                         '; 	% (Peter Liddle)
'arthur@marzen.ucdavis.edu                   ';		% (Arthur)
'neilc@wallaby.Stanford.EDU                  ';		% (Neil Crellin)
'haacke@mirlink.wustl.edu                    ';		% (Mark Haacke)
'L.vanErning@rdiag.azn.nl                    ';		% (Leon van Erning)
'andrew.martin@utmb.edu                      ';  	% (Andrew Martin)
'desudct@ccfadm.eeg.ccf.org                  ';		% (Tayard Desudcht)
'B.vanderKallen@rdiag.azn.nl                 ';		% (Bas van der Kallen)
'pk.marsden@umds.ac.uk                       ';		% (Paul Marsden)
'amartin@beach.utmb.edu                      ';		% (Andrew Martin)
'oesterle@sun1.ukl.uni-freiburg.de           ';		% (Claudia Oesterle)
'k.nijran@cxwms.ac.uk                        ';		% (Kuldip Nijran)
'ward@psyphy.psych.wisc.edu                  ';  	% (Terry Ward)
'dwikler@ulb.ac.be                           ';  	% (David Wilker)
'danpavel@uic.edu                            ';  	% (Dan Pavel)
'SDERBYSH@fs1.hope-hospital.manchester.ac.uk ';  	% (Stuart Derbyshire)
'wjjagust@lbl.gov                            ';		% (William Jagust)
'strupp@geronimo.drad.umn.edu                ';		% (John Strupp)
'grmangun@ucdavis.edu                        ';		% (Ron Mangun)
'spjujcm@ucl.ac.uk                           ';		% (John Mellers)
'epaulesu@gea.hsr.it                         ';		% (Eraldo Paulesu)
'spjugfb@ucl.ac.uk                           ';		% (Geraldo Busatto)
'tron@atomki.hu                              ';		% (Lajos Tron)
'schlor01@mcgc16.med.nyu.edu                 ';		% (Ralf Schloesser)
'brodij01@mcgc16.med.nyu.edu                 ';		% (Jonathan Brodie)
'martini@neuro.ks.se                         ';		% (Martin Ingvar)
'sflitman@helix.nih.gov                      ';		% (Stephen Flitman)
'Douglas.Steele@ed.ac.uk                     ';		% (Douglas Steele)
'dasilber@med.cornell.edu                    ';		% (David Silbersweig)
'James_Prichard@QuickMail.Yale.edu           ';		% (James Prichard)
'devous@UTSW.SWMED.EDU                       ';		% (Michael Devous)
'sho@clarke-inst.on.ca                       ';		% (Sylvain Houle)
'tearly@brain.utmb.edu                       ';		% (Terrence Early)
'avane@brain.utmb.edu                        ';		% (Zorik Avanessian)
'jjmann@neuron.cpmc.columbia.edu             ';		% (John Mann)
'campbell@neuron.cpmc.columbia.edu           ';		% (Carl Campbell)
'onxwi01@mailserv.zdv.uni-tuebingen.de       ';		% (tubingen)
'OUTI.SIPILA@LTK.HYKS.HYKS.mailnet.fi        ';		% (Outi Sipil{)
'kiebel@neuroinformatik.ruhr-uni-bochum.de   ';		% (Stefan Kiebel)
'stephan@leukos.neurologie.uni-duesseldorf.de';		% (Klaus Stephan)
'alan@prometheus.nucmed.buffalo.edu          ';		% (Alan Lockwood)
'ALBERT@medfysik.aau.dk                      ';		% (Albert Gjedde)
'tracy@oracle.medimg.emory.edu               ';		% (Tracy Faber)
'astaire@alw.nih.gov                         ';		% (Vicente Ibanez)
'gur@bbl.psycha.upenn.edu                    ';		% (Ruben Gur)
'zhao@umbc.edu                               ';		% (Margaret Zhao)
'marie@cerim.insa-lyon.fr                    ';		% (MarieClaude Gregoire)
'Neil_Weisenfeld@nih.gov                     ';		% (Neil Weisenfeld)
'braun@alw.nih.gov                           ';		% (Allen Braun)
'gfe@pet1.austin.unimelb.edu.au              ';		% (Gray Egan)
'steve%vapet.uucp@cs.umn.edu                 ';		% (Steven Strother)
'nelson@max.uh.cwru.edu                      ';		% (Dennis Nelson)
'ellert@amber.uh.cwru.edu                    ';		% (Ed ellert)
'Jael.Travere@Cyceron.Fr                     ';		% (Joel Travere)
'randy@tessa.iaf.uiowa.edu                   ';		% (Randall Frank)
'nichols@willard.pet.upmc.edu                ';		% (Thomas Nichols)
'jtlee@james.psych.umn.edu                   ';		% (Joel Lee)	
'suren@cortex.mb.jhu.edu                     ';		% (Surendar Nathan)
'dmcmanus@siumed.edu                         ';		% (Dennis Q. McManus)
'boonhwee@deanwong.rad.jhu.edu               ';		% (Boon Hwee Chan)
'vapet!jvpardo@cs.umn.edu                    ';		% (Jose Pardo)
'mtw@cortex.mhri.edu.au                      ';		% (Michael Wong)
'resnick%mvx.dnet@dxi.nih.gov                ';		% (Susan Resnick)
'beattie@poincare.mskcc.org                  ';		% (Bradley Beattie)
'cmdnca@mhvax.weeg.uiowa.edu                 ';		% (Nancy Andreasen)
'sadato@alw.nih.gov                          ';		% (Norihiro Sadato)
'hallett@helix.nih.gov                       ';		% (Mark Hallett)
'jhsiao@helix.nih.gov                        ';		% (John Hsiao)
'GWOOD@irp.nida.nih.gov                      ';		% (Greg Wood)
'dubois@nefy.ucl.ac.be                       ';		% (Dubois Samuel)
'mazoyer@uriens.shfj.cea.fr                  ';		% (Bernard Mazoyer)
'yun@enuxsa.eas.asu.edu                      ';		% (Lang-Sheng Yun)
'WEINBERD@dirpc.nimh.nih.gov                 ';		% (Dan Weinberger)
'hanif@petnet.buffalo.edu                    ';		% (Hanif Khalak)
'Mike_Glabus@edinburgh.ac.uk                 ';		% (Mike Glabus)
'b51239@sakura.kudpc.kyoto-u.ac.jp           ';		% (Hidenao Fukuyama)
'sean@pet.mni.mcgill.ca                      ';		% (Sean Marrett)
'HIRSCH@vision.mskcc.org                     ';		% (Joy Hirsch)
'TNK060@VM.HRZ.UNI-ESSEN.DE                  ';		% (Cornelius Weiller)
'grabowsk@blue.weeg.uiowa.edu                ';		% (Thomas Grabowski)
'rparks@siumed.edu                           ';		% (Randolph Parks)
'apolis@helix.nih.gov                        ';		% (Alan Polis)
'john.missimer@psi.ch                        ';		% (John Missimer)
'paul.maguire@psi.ch                         ';		% (Paul Maguire)
'f54225@sakura.kudpc.kyoto-u.ac.jp           ';		% (Hiroshi Shibasaki)
'fred@ncbapsun2.pet.wfu.edu                  ';		% (Fred Fahey)
'epmp08@uk.ac.ed.castle                      ';		% (Mike Glabus)
'colem010@hermes1.mc.duke.edu                ';		% (Ed Coleman)
'gage@donald.medeng.wfu.edu                  ';		% (Don Gage)
'grady@alw.nih.gov                           ';		% (Cheryl Grady)
'salmon@pet.crc.ulg.ac.be                    ';		% (Eric Salmon)
'ggoodwin@srv1.bmu.mrc.ac.uk                 ';      	% (Guy Goodwin)
'Patrick.Dupont@uz.kuleuven.ac.be            ';		% (Patrick Dupont)
'mcintosh@psych.toronto.edu                  ';		% (Randy Mcintosh)
'cbrown@interramp.com                        ';		% (Charles Brown)
'IJT7SMB@MVS.OAC.UCLA.EDU                    ';		% (Steve Berman)
'leuchter@loni.ucla.edu                      ';		% (Andy Leuchter)
'bill2@meg.psyhsc.sunysb.edu                 ';		% (William Tew)
'LDELISI@ccmail.sunysb.edu                   ';		% (Lynn Delisi)
'jc5e+@andrew.cmu.edu                        ';		% (Jonathan Cohen)
'anders@ziggy.med.yale.edu                   ';		% (Adam Anderson)
'bchen@hsc.usc.edu                           ';		% (Benjamin Chen)
'mandelkern@hep.phy.cam.ac.uk                ';		% (Mark Mandelkern)
'lim@isl.stanford.edu                        ';
'snathan@eureka.wbme.jhu.edu                 ';
'dwong@welchlink.welch.jhu.edu               ';
'marc@npg.wustl.edu                          ';		% (Marc Raichle)
'sep@npg.wustl.edu                           ';		% (Steve Petersen)
'peter_fox@biad23.uthscsa.edu                ';		% (Peter Fox)
'jack_lancaster@biad23.uthscsa.edu           ';		% (Jack Lancaster)
'hunter_downs@biad23.uthscsa.edu             ';		% (Hunter Downs)
'hal@petadmin.wustl.edu                      ';		% (John Haller)
'peterj@zeus.nhlbi.nih.gov                   '; 	% (Peter Jezzard)
'daphne@lnp.salk.edu                         ';
'jwatson@atom.ansto.gov.au                   '; 	% (John Watson)
'andrew@stats.gla.ac.uk                      '; 	% (Andrew Holmes)
'nahmias@fhs.csu.McMaster.CA                 '; 	% (Claude Nahmias)
'babak@acsu.buffalo.edu                      ';
'keith@zaphod.math.mcgill.ca                 '; 	% (Keith Worsley)
'reddy@nucmed.med.nyu.edu                    '; 	% (David Reddy)
'SCHNEIDER@vms.cis.pitt.edu                  '; 	% (Walter Schneider)
'mazz@loni.ucla.edu                          '; 	% (John Mazziotta)
'bilder@aecom.yu.edu                         '; 	% (Bob Bilder)
'smk@huelings.harvard.edu                    '; 	% (Stephen Kosslyn)
'haxby@alw.nih.gov                           '; 	% (Jin Haxby)
'joem@alw.nih.gov                            ';
'alpert@petw5.mgh.harvard.edu                '; 	% (Nat Alpert)
'lange@alw.nih.gov                           '; 	% (Nick Lange)
'maquet@pet.crc.ulg.ac.be                    '; 	% (Pierre Maquet)
'tetsuji@rai.juice.or.jp                     '; 	% (Rai Tetsuji)
'RDLANE@CCIT.ARIZONA.EDU                     '; 	% (Richard D. Lane)
'levin@helix.nih.gov                         '; 	% (Ron Levin)
'bermank@alw.nih.gov                         '; 	% (Karen Berman)
'tim@petsparc.mc.duke.edu                    '; 	% (Tim Turkington)
'degueldr@pet.crc.ulg.ac.be                  ';		% (Christian Degueldre)
'neville@lnp.UCSD.EDU                        '; 	% (Helen Neville)
'lgu@ln.nimh.nih.gov                         ';		% (Leslie Ungerleider)
'sing@wrair-emh1.army.mil                    '; 	% (Helen Sing)
'zeffiro@alw.nih.gov                         '; 	% (Tom Zeffiro)
'kruger@wilber.med.jhu.edu                   '; 	% (Mark Kruger)
'mjs@wilber.med.jhu.edu                      '; 	% (Martin Stumpf)
'jd@lri.stjosephs.london.on.ca               '; 	% (J. Davis)
'JTBECKER@vms.cis.pitt.edu                   '; 	% (James Becker)
'csvarer@ei.dth.dk                           ';		% (Claus Svarer)
'KEBMEIER@srv1.bmu.mrc.ac.uk                 ';		% (Klaus Ebmeier)
'vanhorn@alw.nih.gov                         ';		% (John Van Horn)
'gpca12@udcf.gla.ac.uk                       ';		% (Dr David Wyper)
'brian@petnet.buffalo.edu                    '];	% (Brian Murphy)


% send spm_UPDATE
%---------------------------------------------------------------------------
for i = 1:size(P,1)
	d = P(i,:);
%	s = ['mail -s SPM95 < spm_UPDATE ' d(d ~= ' ')]
%	s = ['mail -s "SPM-Help Mailing List" < spm-help.announce ' d(d ~= ' ')]
%	unix(s);
end
