function opts = spm_config_checkreg
% Configuration file for check-reg jobs
%_______________________________________________________________________
% Copyright (C) 2005 Wellcome Department of Imaging Neuroscience

% John Ashburner
% $Id: spm_config_checkreg.m 171 2005-05-20 19:20:10Z john $

data.type = 'files';
data.name = 'Images to Display';
data.tag  = 'data';
data.filter = 'image';
data.num  = [1 15];
data.help = {'Images to display.'};

opts.type = 'branch';
opts.name = 'Check Registration';
opts.tag  = 'checkreg';
opts.val  = {data};
opts.prog = @dispims;
opts.help = {[...
'Orthogonal views of one or more images are displayed.  Clicking in '...
'any image moves the centre of the orthogonal views.  Images are '...
'shown in orientations relative to that of the first selected image. '...
'The first specified image is shown at the top-left, and the last at '...
'the bottom right.  The fastest increment is in the left-to-right '...
'direction (the same as you are reading this).'],...
'',...
['If you have put your images in the correct file format, ',...
 'then (possibly after specifying some rigid-body rotations):'],...
['    The top-left image is coronal with the top (superior) ',...
 'of the head displayed at the top and the left shown on the left. ',...
 'This is as if the subject is viewed from behind.'],...
['    The bottom-left image is axial with the front (anterior) of the ',...
 'head at the top and the left shown on the left. ',...
 'This is as if the subject is viewed from above.'],...
['    The top-right image is sagittal with the front (anterior) of ',...
 'the head at the left and the top of the head shown at the top. ',...
 'This is as if the subject is viewed from the left.']};
%------------------------------------------------------------------------

%------------------------------------------------------------------------
function dispims(varargin)
job = strvcat(varargin{1}.data);
spm_check_registration(job);
return;
