function spm_graph_ui(h)
% user interface for graphs
% FORMAT spm_graph_ui(h)
% h - axis handle
%_______________________________________________________________________
% %W% Karl Friston %E%

% get tags and strings
%-----------------------------------------------------------------------
Fgraph = spm_figure('FindWin','Graphics');
Finter = spm_figure('FindWin','Interactive');
spm_clf(Finter);
set(h,'Tag','TAG')
H      = 'findobj(''Tag'',''TAG'')';
WS     = spm('GetWinScale');
y      = 300;
dy     = 30;

% Title
%-----------------------------------------------------------------------
uicontrol(Finter,'Style','Text',...
	'String','Title',...
	'Position',[020 y 80 016].*WS);
uicontrol(Finter,'Style','Edit',...
	'String',get(get(h,'Title'),'String'),...
	'Callback',['set(get(' H ',''Title''),''String'',get(gco,''String''));'],...
	'Position',[150 y 200 016].*WS,'Interruptible','yes');
y      = y - dy;


% XLabel
%-----------------------------------------------------------------------
uicontrol(Finter,'Style','Text',...
	'String','x Label',...
	'Position',[020 y 80 016].*WS);
uicontrol(Finter,'Style','Edit',...
	'String',get(get(h,'XLabel'),'String'),...
	'Callback',['set(get(' H ',''XLabel''),''String'',get(gco,''String''));'],...
	'Position',[150 y 200 016].*WS,'Interruptible','yes');
y      = y - dy;


% YLabel
%-----------------------------------------------------------------------
uicontrol(Finter,'Style','Text',...
	'String','y Label',...
	'Position',[020 y 80 016].*WS);
uicontrol(Finter,'Style','Edit',...
	'String',get(get(h,'YLabel'),'String'),...
	'Callback',['set(get(' H ',''YLabel''),''String'',get(gco,''String''));'],...
	'Position',[150 y 200 016].*WS,'Interruptible','yes');
y      = y - dy;


% LineWidth
%-----------------------------------------------------------------------
uicontrol(Finter,'Style','Text',...
	'String','LineWidth',...
	'Position',[020 y 80 016].*WS);
uicontrol(Finter,'Style','Edit',...
	'String',get(h,'LineWidth'),...
	'Callback',['set(' H ',''LineWidth'',eval(get(gco,''String'')));'],...
	'Position',[150 y 200 016].*WS,'Interruptible','yes');
y      = y - dy;

% XLim
%-----------------------------------------------------------------------
uicontrol(Finter,'Style','Text',...
	'String','x axis',...
	'Position',[020 y 80 016].*WS);
uicontrol(Finter,'Style','Edit',...
	'String',sprintf('%0.1f %0.1f',get(h,'XLim')),...
	'Callback',['set(' H ',''XLim'',eval([ '' [ '' get(gco,''String'') '' ] '']));'],...
	'Position',[150 y 200 016].*WS,'Interruptible','yes');
y      = y - dy;


% YLim
%-----------------------------------------------------------------------
uicontrol(Finter,'Style','Text',...
	'String','y axis',...
	'Position',[020 y 80 016].*WS);
uicontrol(Finter,'Style','Edit',...
	'String',sprintf('%0.1f %0.1f',get(h,'YLim')),...
	'Callback',['set(' H ',''YLim'',eval([ '' [ '' get(gco,''String'') '' ] '']));'],...
	'Position',[150 y 200 016].*WS,'Interruptible','yes');
y      = y - dy;



% Other attributes
%-----------------------------------------------------------------------
uicontrol(Finter,'Style','Pushbutton','String','hold on','Callback',...
	['set(' H ',''NextPlot'',''add'');'],...
	 'Position',[020 y 60 20].*WS,'Interruptible','yes');

uicontrol(Finter,'Style','Pushbutton','String','off','Callback',...
	['set(' H ',''NextPlot'',''replace'');'],...
	 'Position',[080 y 30 20].*WS,'Interruptible','yes');

uicontrol(Finter,'Style','Pushbutton','String','Grid on','Callback',...
	['set(' H ',''XGrid'',''on'',''YGrid'',''on'');'],...
	 'Position',[140 y 60 20].*WS,'Interruptible','yes');

uicontrol(Finter,'Style','Pushbutton','String','off','Callback',...
	['set(' H ',''XGrid'',''off'',''YGrid'',''off'');'],...
	 'Position',[200 y 30 20].*WS,'Interruptible','yes');

uicontrol(Finter,'Style','Pushbutton','String','Box on','Callback',...
	['set(' H ',''Box'',''on'');'],...
	 'Position',[260 y 60 20].*WS,'Interruptible','yes');

uicontrol(Finter,'Style','Pushbutton','String','off','Callback',...
	['set(' H ',''Box'',''off'');'],...
	 'Position',[320 y 30 20].*WS,'Interruptible','yes');

y      = y - dy;

uicontrol(Finter,'Style','Pushbutton','String','Square','Callback',...
	['set(' H ',''AspectRatio'',[1 NaN]);'],...
	 'Position',[020 y 60 20].*WS,'Interruptible','yes');

uicontrol(Finter,'Style','Pushbutton','String','Auto','Callback',...
	['set(' H ',''AspectRatio'',[NaN NaN]);'],...
	 'Position',[080 y 60 20].*WS,'Interruptible','yes');

