/*
 * MATLAB Compiler: 4.1 (R14SP1)
 * Date: Fri Mar  4 14:05:47 2005
 * Arguments: "-B" "macro_default" "-m" "-W" "main" "-T" "link:exe" "-v" "-o"
 * "jobman_GLNX86" "exec_jobman.m" "spm_load.m" "-I" "/home/john/spm" "-R"
 * "-nojvm" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_jobman_GLNX86_public_data[] = {'3', '0', '8', '1',
                                                         '9', 'D', '3', '0',
                                                         '0', 'D', '0', '6',
                                                         '0', '9', '2', 'A',
                                                         '8', '6', '4', '8',
                                                         '8', '6', 'F', '7',
                                                         '0', 'D', '0', '1',
                                                         '0', '1', '0', '1',
                                                         '0', '5', '0', '0',
                                                         '0', '3', '8', '1',
                                                         '8', 'B', '0', '0',
                                                         '3', '0', '8', '1',
                                                         '8', '7', '0', '2',
                                                         '8', '1', '8', '1',
                                                         '0', '0', 'C', '4',
                                                         '9', 'C', 'A', 'C',
                                                         '3', '4', 'E', 'D',
                                                         '1', '3', 'A', '5',
                                                         '2', '0', '6', '5',
                                                         '8', 'F', '6', 'F',
                                                         '8', 'E', '0', '1',
                                                         '3', '8', 'C', '4',
                                                         '3', '1', '5', 'B',
                                                         '4', '3', '1', '5',
                                                         '2', '7', '7', 'E',
                                                         'D', '3', 'F', '7',
                                                         'D', 'A', 'E', '5',
                                                         '3', '0', '9', '9',
                                                         'D', 'B', '0', '8',
                                                         'E', 'E', '5', '8',
                                                         '9', 'F', '8', '0',
                                                         '4', 'D', '4', 'B',
                                                         '9', '8', '1', '3',
                                                         '2', '6', 'A', '5',
                                                         '2', 'C', 'C', 'E',
                                                         '4', '3', '8', '2',
                                                         'E', '9', 'F', '2',
                                                         'B', '4', 'D', '0',
                                                         '8', '5', 'E', 'B',
                                                         '9', '5', '0', 'C',
                                                         '7', 'A', 'B', '1',
                                                         '2', 'E', 'D', 'E',
                                                         '2', 'D', '4', '1',
                                                         '2', '9', '7', '8',
                                                         '2', '0', 'E', '6',
                                                         '3', '7', '7', 'A',
                                                         '5', 'F', 'E', 'B',
                                                         '5', '6', '8', '9',
                                                         'D', '4', 'E', '6',
                                                         '0', '3', '2', 'F',
                                                         '6', '0', 'C', '4',
                                                         '3', '0', '7', '4',
                                                         'A', '0', '4', 'C',
                                                         '2', '6', 'A', 'B',
                                                         '7', '2', 'F', '5',
                                                         '4', 'B', '5', '1',
                                                         'B', 'B', '4', '6',
                                                         '0', '5', '7', '8',
                                                         '7', '8', '5', 'B',
                                                         '1', '9', '9', '0',
                                                         '1', '4', '3', '1',
                                                         '4', 'A', '6', '5',
                                                         'F', '0', '9', '0',
                                                         'B', '6', '1', 'F',
                                                         'C', '2', '0', '1',
                                                         '6', '9', '4', '5',
                                                         '3', 'B', '5', '8',
                                                         'F', 'C', '8', 'B',
                                                         'A', '4', '3', 'E',
                                                         '6', '7', '7', '6',
                                                         'E', 'B', '7', 'E',
                                                         'C', 'D', '3', '1',
                                                         '7', '8', 'B', '5',
                                                         '6', 'A', 'B', '0',
                                                         'F', 'A', '0', '6',
                                                         'D', 'D', '6', '4',
                                                         '9', '6', '7', 'C',
                                                         'B', '1', '4', '9',
                                                         'E', '5', '0', '2',
                                                         '0', '1', '1', '1'
                                                         , '\0'};

const char *__MCC_jobman_GLNX86_name_data = "jobman_GLNX86";

const char *__MCC_jobman_GLNX86_root_data = "";

const unsigned char __MCC_jobman_GLNX86_session_data[] = {'A', '0', '9', 'E',
                                                          '2', 'A', '9', '7',
                                                          'F', '1', '9', '6',
                                                          '7', 'D', '2', '5',
                                                          'C', '4', 'A', '6',
                                                          'D', 'C', '2', '3',
                                                          'A', '0', '4', '1',
                                                          'B', '1', '3', '1',
                                                          'F', 'C', 'A', '2',
                                                          '9', '1', '3', '6',
                                                          '8', 'D', '0', 'B',
                                                          '9', '2', '6', 'A',
                                                          '3', '1', 'F', '2',
                                                          '6', '5', 'E', '7',
                                                          '9', 'D', '2', '3',
                                                          '3', '7', 'E', '0',
                                                          '8', '4', '2', '8',
                                                          '9', '7', 'C', '4',
                                                          '3', '6', '8', '6',
                                                          'A', 'C', 'F', '0',
                                                          '9', '5', '5', 'E',
                                                          'F', 'A', '8', '0',
                                                          '7', '0', '4', '0',
                                                          '1', '4', '0', '3',
                                                          'E', 'C', 'A', '1',
                                                          '5', 'E', 'E', 'E',
                                                          'C', '3', 'C', 'A',
                                                          '8', 'A', '5', 'C',
                                                          'F', '8', 'B', '4',
                                                          '0', '4', '8', '7',
                                                          '2', 'A', '6', '1',
                                                          '5', 'C', '7', 'A',
                                                          '8', '2', 'A', '8',
                                                          '6', '7', 'B', 'C',
                                                          'E', 'D', '8', '7',
                                                          '6', '5', '2', 'A',
                                                          '9', 'A', 'C', '9',
                                                          'B', '2', 'C', 'E',
                                                          'B', '9', '2', 'E',
                                                          '3', 'F', '3', '1',
                                                          'E', 'B', '0', '0',
                                                          'D', 'C', '8', '1',
                                                          'A', '5', '9', '3',
                                                          '6', '5', '3', '5',
                                                          'F', '3', 'A', '1',
                                                          '1', '5', 'A', 'A',
                                                          '9', '3', '1', '4',
                                                          '6', 'B', '0', '0',
                                                          '6', '6', '7', '5',
                                                          'B', '9', 'B', '2',
                                                          '2', 'F', 'A', 'F',
                                                          '1', 'E', '5', 'C',
                                                          'B', '1', 'E', 'F',
                                                          'B', 'D', '0', '7',
                                                          'A', 'E', '1', 'E',
                                                          'F', '3', '5', '3',
                                                          '4', '0', '0', '6',
                                                          '4', '9', '8', '3',
                                                          'B', 'B', 'F', 'F',
                                                          'E', '1', 'F', 'A',
                                                          'D', 'D', 'C', 'A',
                                                          'C', 'D', '7', '7',
                                                          '1', '0', 'E', 'D',
                                                          '9', '4', '9', '0'
                                                          , '\0'};

const char *__MCC_jobman_GLNX86_matlabpath_data[] = {"jobman_GLNX86/",
                                                     "toolbox/compiler/deploy/",
                                                     "home/john/spm/",
                                                     "home/john/matlab/",
                                                     "$TOOLBOXMATLABDIR/general/",
                                                     "$TOOLBOXMATLABDIR/ops/",
                                                     "$TOOLBOXMATLABDIR/lang/",
                                                     "$TOOLBOXMATLABDIR/elmat/",
                                                     "$TOOLBOXMATLABDIR/elfun/",
                                                     "$TOOLBOXMATLABDIR/specfun/",
                                                     "$TOOLBOXMATLABDIR/matfun/",
                                                     "$TOOLBOXMATLABDIR/datafun/",
                                                     "$TOOLBOXMATLABDIR/polyfun/",
                                                     "$TOOLBOXMATLABDIR/funfun/",
                                                     "$TOOLBOXMATLABDIR/sparfun/",
                                                     "$TOOLBOXMATLABDIR/scribe/",
                                                     "$TOOLBOXMATLABDIR/graph2d/",
                                                     "$TOOLBOXMATLABDIR/graph3d/",
                                                     "$TOOLBOXMATLABDIR/specgraph/",
                                                     "$TOOLBOXMATLABDIR/graphics/",
                                                     "$TOOLBOXMATLABDIR/uitools/",
                                                     "$TOOLBOXMATLABDIR/strfun/",
                                                     "$TOOLBOXMATLABDIR/imagesci/",
                                                     "$TOOLBOXMATLABDIR/iofun/",
                                                     "$TOOLBOXMATLABDIR/audiovideo/",
                                                     "$TOOLBOXMATLABDIR/timefun/",
                                                     "$TOOLBOXMATLABDIR/datatypes/",
                                                     "$TOOLBOXMATLABDIR/verctrl/",
                                                     "$TOOLBOXMATLABDIR/codetools/",
                                                     "$TOOLBOXMATLABDIR/helptools/",
                                                     "$TOOLBOXMATLABDIR/demos/",
                                                     "toolbox/local/",
                                                     "toolbox/compiler/",
                                                     "toolbox/nnet/nnet/",
                                                     "toolbox/nnet/nnutils/",
                                                     "toolbox/signal/signal/",
                                                     "toolbox/symbolic/"};
const int __MCC_jobman_GLNX86_matlabpath_data_count = 37;

const char *__MCC_jobman_GLNX86_classpath_data[] = { "" };
const int __MCC_jobman_GLNX86_classpath_data_count = 0;

const char *__MCC_jobman_GLNX86_mcr_application_options[] = {"-nojvm"};
const int __MCC_jobman_GLNX86_mcr_application_option_count = 1;
const char *__MCC_jobman_GLNX86_mcr_runtime_options[] = { "" };
const int __MCC_jobman_GLNX86_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


