/*
 * MATLAB Compiler: 4.1 (R14SP1)
 * Date: Fri Mar  4 14:05:12 2005
 * Arguments: "-B" "macro_default" "-m" "-W" "main" "-T" "link:exe" "-v" "-o"
 * "spm_GLNX86" "exec_spm.m" "spm_load.m" "-I" "/home/john/spm" "-R" "-nojvm" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_spm_GLNX86_public_data[] = {'3', '0', '8', '1', '9',
                                                      'D', '3', '0', '0', 'D',
                                                      '0', '6', '0', '9', '2',
                                                      'A', '8', '6', '4', '8',
                                                      '8', '6', 'F', '7', '0',
                                                      'D', '0', '1', '0', '1',
                                                      '0', '1', '0', '5', '0',
                                                      '0', '0', '3', '8', '1',
                                                      '8', 'B', '0', '0', '3',
                                                      '0', '8', '1', '8', '7',
                                                      '0', '2', '8', '1', '8',
                                                      '1', '0', '0', 'C', '4',
                                                      '9', 'C', 'A', 'C', '3',
                                                      '4', 'E', 'D', '1', '3',
                                                      'A', '5', '2', '0', '6',
                                                      '5', '8', 'F', '6', 'F',
                                                      '8', 'E', '0', '1', '3',
                                                      '8', 'C', '4', '3', '1',
                                                      '5', 'B', '4', '3', '1',
                                                      '5', '2', '7', '7', 'E',
                                                      'D', '3', 'F', '7', 'D',
                                                      'A', 'E', '5', '3', '0',
                                                      '9', '9', 'D', 'B', '0',
                                                      '8', 'E', 'E', '5', '8',
                                                      '9', 'F', '8', '0', '4',
                                                      'D', '4', 'B', '9', '8',
                                                      '1', '3', '2', '6', 'A',
                                                      '5', '2', 'C', 'C', 'E',
                                                      '4', '3', '8', '2', 'E',
                                                      '9', 'F', '2', 'B', '4',
                                                      'D', '0', '8', '5', 'E',
                                                      'B', '9', '5', '0', 'C',
                                                      '7', 'A', 'B', '1', '2',
                                                      'E', 'D', 'E', '2', 'D',
                                                      '4', '1', '2', '9', '7',
                                                      '8', '2', '0', 'E', '6',
                                                      '3', '7', '7', 'A', '5',
                                                      'F', 'E', 'B', '5', '6',
                                                      '8', '9', 'D', '4', 'E',
                                                      '6', '0', '3', '2', 'F',
                                                      '6', '0', 'C', '4', '3',
                                                      '0', '7', '4', 'A', '0',
                                                      '4', 'C', '2', '6', 'A',
                                                      'B', '7', '2', 'F', '5',
                                                      '4', 'B', '5', '1', 'B',
                                                      'B', '4', '6', '0', '5',
                                                      '7', '8', '7', '8', '5',
                                                      'B', '1', '9', '9', '0',
                                                      '1', '4', '3', '1', '4',
                                                      'A', '6', '5', 'F', '0',
                                                      '9', '0', 'B', '6', '1',
                                                      'F', 'C', '2', '0', '1',
                                                      '6', '9', '4', '5', '3',
                                                      'B', '5', '8', 'F', 'C',
                                                      '8', 'B', 'A', '4', '3',
                                                      'E', '6', '7', '7', '6',
                                                      'E', 'B', '7', 'E', 'C',
                                                      'D', '3', '1', '7', '8',
                                                      'B', '5', '6', 'A', 'B',
                                                      '0', 'F', 'A', '0', '6',
                                                      'D', 'D', '6', '4', '9',
                                                      '6', '7', 'C', 'B', '1',
                                                      '4', '9', 'E', '5', '0',
                                                      '2', '0', '1', '1', '1'
                                                      , '\0'};

const char *__MCC_spm_GLNX86_name_data = "spm_GLNX86";

const char *__MCC_spm_GLNX86_root_data = "";

const unsigned char __MCC_spm_GLNX86_session_data[] = {'4', '1', '2', 'B',
                                                       '2', 'D', 'A', '8',
                                                       'F', '9', '0', '6',
                                                       '9', '5', '0', 'C',
                                                       '9', '4', '0', 'D',
                                                       '3', 'F', '5', '9',
                                                       '6', 'D', '7', '7',
                                                       '4', 'A', 'E', '2',
                                                       'E', '0', '4', '6',
                                                       '6', '5', 'E', 'B',
                                                       '4', 'D', '6', 'C',
                                                       'A', '6', 'D', 'E',
                                                       'A', '8', '7', 'B',
                                                       'F', '3', '5', '8',
                                                       '5', '7', 'F', '2',
                                                       'B', 'D', '8', '3',
                                                       'C', 'E', 'A', '7',
                                                       '0', 'F', 'F', '3',
                                                       '6', 'F', 'B', '2',
                                                       '1', 'E', '4', '4',
                                                       '6', 'D', '4', 'F',
                                                       '2', 'F', '7', 'C',
                                                       '1', '9', '0', '5',
                                                       '9', '0', '7', '3',
                                                       '5', '6', '6', '6',
                                                       'A', 'A', 'A', 'A',
                                                       'B', 'C', 'F', '0',
                                                       'C', '1', '7', '8',
                                                       '3', 'B', 'E', 'D',
                                                       '8', 'E', '1', '9',
                                                       '8', 'A', '4', 'C',
                                                       '4', '9', '5', 'E',
                                                       '0', '8', 'D', '6',
                                                       'B', '2', 'D', '9',
                                                       '6', '2', '0', '5',
                                                       'A', '4', 'B', '2',
                                                       '3', 'B', '8', '8',
                                                       'C', '4', '1', '7',
                                                       'B', '7', '9', '8',
                                                       'D', '1', '2', '3',
                                                       '7', '6', 'E', '6',
                                                       'C', '3', '6', '8',
                                                       '3', 'B', 'F', 'A',
                                                       '3', 'E', 'D', 'E',
                                                       '0', 'C', '8', '1',
                                                       '3', '9', 'F', '0',
                                                       '9', 'E', 'D', '5',
                                                       '2', 'E', '6', '7',
                                                       'C', '9', 'C', 'D',
                                                       '9', '1', '6', '2',
                                                       'F', 'B', 'A', '5',
                                                       '1', '3', '6', 'F',
                                                       '0', 'C', 'E', '0',
                                                       '3', 'A', 'A', 'C',
                                                       'A', '9', 'A', '6',
                                                       '8', 'B', 'A', '0',
                                                       '6', 'D', 'F', '7',
                                                       'D', '0', 'F', '4',
                                                       '9', '3', '9', '3',
                                                       'A', '1', 'F', '8',
                                                       '3', '8', '8', 'D',
                                                       'C', '1', '9', 'C',
                                                       '7', 'A', 'D', '8',
                                                       '1', '7', '2', '3'
                                                       , '\0'};

const char *__MCC_spm_GLNX86_matlabpath_data[] = {"spm_GLNX86/",
                                                  "toolbox/compiler/deploy/",
                                                  "home/john/spm/",
                                                  "home/john/matlab/",
                                                  "$TOOLBOXMATLABDIR/general/",
                                                  "$TOOLBOXMATLABDIR/ops/",
                                                  "$TOOLBOXMATLABDIR/lang/",
                                                  "$TOOLBOXMATLABDIR/elmat/",
                                                  "$TOOLBOXMATLABDIR/elfun/",
                                                  "$TOOLBOXMATLABDIR/specfun/",
                                                  "$TOOLBOXMATLABDIR/matfun/",
                                                  "$TOOLBOXMATLABDIR/datafun/",
                                                  "$TOOLBOXMATLABDIR/polyfun/",
                                                  "$TOOLBOXMATLABDIR/funfun/",
                                                  "$TOOLBOXMATLABDIR/sparfun/",
                                                  "$TOOLBOXMATLABDIR/scribe/",
                                                  "$TOOLBOXMATLABDIR/graph2d/",
                                                  "$TOOLBOXMATLABDIR/graph3d/",
                                                  "$TOOLBOXMATLABDIR/specgraph/",
                                                  "$TOOLBOXMATLABDIR/graphics/",
                                                  "$TOOLBOXMATLABDIR/uitools/",
                                                  "$TOOLBOXMATLABDIR/strfun/",
                                                  "$TOOLBOXMATLABDIR/imagesci/",
                                                  "$TOOLBOXMATLABDIR/iofun/",
                                                  "$TOOLBOXMATLABDIR/audiovideo/",
                                                  "$TOOLBOXMATLABDIR/timefun/",
                                                  "$TOOLBOXMATLABDIR/datatypes/",
                                                  "$TOOLBOXMATLABDIR/verctrl/",
                                                  "$TOOLBOXMATLABDIR/codetools/",
                                                  "$TOOLBOXMATLABDIR/helptools/",
                                                  "$TOOLBOXMATLABDIR/demos/",
                                                  "toolbox/local/",
                                                  "toolbox/compiler/",
                                                  "toolbox/nnet/nnet/",
                                                  "toolbox/nnet/nnutils/",
                                                  "toolbox/signal/signal/",
                                                  "toolbox/symbolic/"};
const int __MCC_spm_GLNX86_matlabpath_data_count = 37;

const char *__MCC_spm_GLNX86_classpath_data[] = { "" };
const int __MCC_spm_GLNX86_classpath_data_count = 0;

const char *__MCC_spm_GLNX86_mcr_application_options[] = {"-nojvm"};
const int __MCC_spm_GLNX86_mcr_application_option_count = 1;
const char *__MCC_spm_GLNX86_mcr_runtime_options[] = { "" };
const int __MCC_spm_GLNX86_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


