function cfg_basicio_def = cfg_cfg_basicio_def
% 'BasicIO' - MATLABBATCH defaults
% This MATLABBATCH defaults file has been generated automatically
% by MATLABBATCH using ConfGUI. It contains all pre-defined values for
% menu items and provides a full documentation of all fields that may
% be present in a job variable for this application.
% Changes to this file will be overwritten if the ConfGUI batch is executed again.
% Created at 2009-11-20 18:04:58.
cfg_basicio_def.file_move.files = '<UNDEFINED>';
cfg_basicio_def.file_move.action.moveto = '<UNDEFINED>';
cfg_basicio_def.file_move.action.copyto = '<UNDEFINED>';
cfg_basicio_def.file_move.action.moveren.moveto = '<UNDEFINED>';
cfg_basicio_def.file_move.action.moveren.patrep.pattern = '<UNDEFINED>';
cfg_basicio_def.file_move.action.moveren.patrep.repl = '<UNDEFINED>';
cfg_basicio_def.file_move.action.moveren.unique = '<UNDEFINED>';
cfg_basicio_def.file_move.action.copyren.copyto = '<UNDEFINED>';
cfg_basicio_def.file_move.action.copyren.patrep.pattern = '<UNDEFINED>';
cfg_basicio_def.file_move.action.copyren.patrep.repl = '<UNDEFINED>';
cfg_basicio_def.file_move.action.copyren.unique = '<UNDEFINED>';
cfg_basicio_def.file_move.action.delete = false;
cfg_basicio_def.cfg_cd.dir = '<UNDEFINED>';
cfg_basicio_def.cfg_mkdir.parent = '<UNDEFINED>';
cfg_basicio_def.cfg_mkdir.name = '<UNDEFINED>';
cfg_basicio_def.cfg_named_dir.name = '<UNDEFINED>';
cfg_basicio_def.cfg_named_dir.dirs = {'<UNDEFINED>'};
cfg_basicio_def.cfg_named_file.name = '<UNDEFINED>';
cfg_basicio_def.cfg_named_file.files = {'<UNDEFINED>'};
cfg_basicio_def.file_fplist.dir = '<UNDEFINED>';
cfg_basicio_def.file_fplist.filter = '<UNDEFINED>';
cfg_basicio_def.file_fplist.rec = '<UNDEFINED>';
cfg_basicio_def.file_filter.files = '<UNDEFINED>';
cfg_basicio_def.file_filter.typ = '<UNDEFINED>';
cfg_basicio_def.file_filter.filter = '<UNDEFINED>';
cfg_basicio_def.file_filter.frames = '<UNDEFINED>';
cfg_basicio_def.cfg_file_split.name = '<UNDEFINED>';
cfg_basicio_def.cfg_file_split.files = '<UNDEFINED>';
cfg_basicio_def.cfg_file_split.index = {'<UNDEFINED>'};
cfg_basicio_def.cfg_named_input.name = '<UNDEFINED>';
cfg_basicio_def.cfg_named_input.input = '<UNDEFINED>';
cfg_basicio_def.load_vars.matname = '<UNDEFINED>';
cfg_basicio_def.load_vars.loadvars.allvars = true;
cfg_basicio_def.load_vars.loadvars.varname = {'<UNDEFINED>'};
cfg_basicio_def.cfg_save_vars.name = '<UNDEFINED>';
cfg_basicio_def.cfg_save_vars.outdir = '<UNDEFINED>';
cfg_basicio_def.cfg_save_vars.vars.vname = '<UNDEFINED>';
cfg_basicio_def.cfg_save_vars.vars.vcont = '<UNDEFINED>';
cfg_basicio_def.cfg_save_vars.saveasstruct = '<UNDEFINED>';
cfg_basicio_def.subsrefvar.input = '<UNDEFINED>';
cfg_basicio_def.subsrefvar.subsreference.subsfield = '<UNDEFINED>';
cfg_basicio_def.subsrefvar.subsreference.subsindc = {'<UNDEFINED>'};
cfg_basicio_def.subsrefvar.subsreference.subsinda = {'<UNDEFINED>'};
cfg_basicio_def.cfg_assignin.name = '<UNDEFINED>';
cfg_basicio_def.cfg_assignin.output = '<UNDEFINED>';
cfg_basicio_def.runjobs.jobs = '<UNDEFINED>';
cfg_basicio_def.runjobs.inputs{1}.instr = '<UNDEFINED>';
cfg_basicio_def.runjobs.inputs{1}.ineval = '<UNDEFINED>';
cfg_basicio_def.runjobs.inputs{1}.innifti = '<UNDEFINED>';
cfg_basicio_def.runjobs.inputs{1}.inmat = '<UNDEFINED>';
cfg_basicio_def.runjobs.inputs{1}.inany = '<UNDEFINED>';
cfg_basicio_def.runjobs.inputs{1}.indir = '<UNDEFINED>';
cfg_basicio_def.runjobs.save.savejobs.outstub = '<UNDEFINED>';
cfg_basicio_def.runjobs.save.savejobs.outdir = '<UNDEFINED>';
cfg_basicio_def.runjobs.save.dontsave = false;
cfg_basicio_def.runjobs.missing = '<UNDEFINED>';
cfg_basicio_def.call_matlab.inputs.evaluated = '<UNDEFINED>';
cfg_basicio_def.call_matlab.inputs.string = '<UNDEFINED>';
cfg_basicio_def.call_matlab.inputs.anyfile = '<UNDEFINED>';
cfg_basicio_def.call_matlab.inputs.images = '<UNDEFINED>';
cfg_basicio_def.call_matlab.inputs.directory = '<UNDEFINED>';
cfg_basicio_def.call_matlab.outputs.strtype.s = true;
cfg_basicio_def.call_matlab.outputs.strtype.e = true;
cfg_basicio_def.call_matlab.outputs.strtype.n = true;
cfg_basicio_def.call_matlab.outputs.strtype.w = true;
cfg_basicio_def.call_matlab.outputs.strtype.i = true;
cfg_basicio_def.call_matlab.outputs.strtype.r = true;
cfg_basicio_def.call_matlab.outputs.filter.any = true;
cfg_basicio_def.call_matlab.outputs.filter.batch = true;
cfg_basicio_def.call_matlab.outputs.filter.dir = true;
cfg_basicio_def.call_matlab.outputs.filter.image = true;
cfg_basicio_def.call_matlab.outputs.filter.mat = true;
cfg_basicio_def.call_matlab.outputs.filter.mesh = true;
cfg_basicio_def.call_matlab.outputs.filter.nifti = true;
cfg_basicio_def.call_matlab.outputs.filter.xml = true;
cfg_basicio_def.call_matlab.fun = '<UNDEFINED>';
