function [MDP] = spm_MDP_VB_XXX(MDP,OPTIONS)
% active inference and learning using belief propagation (factorised)
% FORMAT [MDP] = spm_MDP_VB_XXX(MDP,OPTIONS)
%
% Input; MDP(m,n)       - structure array of m models over n epochs
% MDP.U(1,Nf)           - controllable factors
% MDP.V(Np,Nf)          - combinations of latent factors (policies)
% MDP.T                 - number of time steps
%
% MDP.A{Ng}(No(g),Ns(1),...,Ns(Nf)) - likelihood of outcomes, given hidden states
% MDP.B{Nf}(Ns(f),Ns(f),Nu(f))      - transitions among states under control states
% MDP.C{Ng}(No(g),1)    - prior probabilities over outcomes       (Dirichlet counts)
% MDP.D{Nf}(Ns(f),1)    - prior probabilities over initial states (Dirichlet counts)
% MDP.E{Nf}(Nu(f),1)    - prior probabilities over paths          (Dirichlet counts)
% MDP.H{Nf}(Ns(f),1)    - prior probabilities over final states   (Dirichlet counts)
%
% MDP.a{Ng,1}           - concentration parameters for A
% MDP.b{Nf,1}           - concentration parameters for B
% MDP.c{Ng,1}           - concentration parameters for C
% MDP.d{Nf,1}           - concentration parameters for D
% MDP.e{Nf,1}           - concentration parameters for E
% MDP.h{Nf}             - concentration parameters for H
%
% optional:
% MDP.s(Nf,T)           - true states   - for each hidden factor
% MDP.u(Nu,T)           - true paths    - for each hidden factor
% MDP.o(Ng,T)           - true outcomes - for each outcome modality
% MDP.O{Ng,T}           - likelihoods   - for each outcome modality
%
% MDP.alpha             - precision - implicit control [512]
% MDP.beta              - precision - active learning [0]
% MDP.chi               - precision - explicit control
% MDP.eta               - Forgetting hyperparameter [128]
% MDP.N                 - depth of deep policy search [N = 0]
% MDP.k(1,Nf)           - beliefs about controllable factors
%
% MDP.id                - domain structure to generate outcomes from
%                         subordinate MDP for deep (hierarchical) models
% MDP.id.hid(Nf,Ni)     - indices of Ni intended  states
% MDP.id.cid(Nf,Ni)     - indices of Ni suprising states
%
% MDP.n(Ng,T)           - outputs for modality g at time T are generated by
%                         agent n(g,T); unless n(g,T) = 0, when outputs
%                         are generated by the agents states.
%                         If n(g,T) < 0, outputs are generated by all
%                         agents
% MDP.m(Nf)             - states for factor f are generated from agent m(f);
%                         unless m(f) = 0, when states are updated for the
%                         agent in question
%
% OPTIONS.B             - switch to evaluate backwards pass (replay)
% OPTIONS.N             - switch to evaluate neuronal responses
% OPTIONS.P             - switch to plot graphics: [default: 0]
% OPTIONS.D             - switch to update initial states with final states
% OPTIONS.BMR           - Bayesian model reduction for multiple trials
%                         see: spm_MDP_VB_sleep(MDP,BMR)
% Outputs:
%
% MDP.P{F}(Nu,T)        - conditional expectations over hidden paths
% MDP.X{F}(Nf,T)        - conditional expectations over hidden states
% MDP.Y{Ng,T}           - conditional expectations over outcomes
% MDP.R(Np,T)           - conditional expectations over policies
%
% MDP.F(1,T)            - (negative) free energies (states)  over time
% MDP.Z{1,T}            - (negative) free energies (control) over time
% MDP.G{1,T}            - (negative) expected free energies  over time
% MDP.Fa                - (negative) free energy of parameters (a)
% MDP.Fb                - ...
%
% MDP.v                 - expected free energy over policies
% MDP.w                 - precision of beliefs about policies
% MDP.un                - simulated neuronal encoding of hidden states
% MDP.xn                - simulated neuronal encoding of policies
% MDP.wn                - simulated neuronal encoding of precision (tonic)
% MDP.dn                - simulated dopamine responses (phasic)
%
% This routine provides solutions of active inference (minimisation of
% variational free energy) using a generative model based upon a Markov
% decision process. The model and inference scheme is formulated in
% discrete space and time. This means that the generative model (and
% process) are hidden Markov models whose dynamics are given by transition
% probabilities among states and the likelihood corresponds to a particular
% outcome conditioned upon hidden states.
%
% This implementation equips agents with the prior beliefs that they will
% maximise expected free energy. Expected free energy can be interpreted in
% several ways - most intuitively as minimising the KL divergence between
% predicted and preferred outcomes (specified as prior beliefs); i.e., risk
% while simultaneously minimising ambiguity. Alternatively, this can be
% rearranged into expected information gain and expected value, where value
% is the log of prior preferences (overstates or outcomes).
%
% This implementation generalises previous MDP based formulations of active
% inference by equipping each factor of latent states with a number of
% paths; some of which may be controllable and others not. Controllable
% factors are now specified with indicator variables in the vector MDP.U.
% Furthermore, because the scheme uses sophisticated inference (i.e., a
% recursive tree search accumulating path integral is of expected free
% energy) a policy reduces to a particular combination of controllable
% paths or dynamics over factors. In consequence, posterior beliefs cover
% latent states and paths; with their associated variational free energies.
% Furthermore, it is now necessary to specify the initial states and the
% initial paths using D and E respectively. In other words, he now plays
% the role of a prior over the path of each factor that can only be changed
% if it is controllable (it no longer corresponds to a prior over
% policies).
%
% In addition to state and path estimation (and policy selection), the
% scheme also updates model parameters; including the state transition
% matrices, mapping to outcomes and the initial state. This is useful for
% learning the context. Likelihood and prior probabilities can be specified
% in terms of concentration parameters (of a Dirichlet distribution
% (a,b,c,...). If the corresponding (A,B,C,...) are supplied, they will be
% used to generate outcomes.
%
% This scheme allows for differences in the functional form of priors –
% specified in terms of probability transition tensors – between the
% generating process and generative model. The generative model is, by
% default, specified in terms of Dirichlet parameters, while the generative
% process is specified in terms of expected (likelihood and prior
% transition) probabilities: A and B, respectively.
%
% This allows the generative model to learn the generative process, when
% the structure or form of the process and its models are the same. If the
% generative process as a different structure (e.g., a different number of
% latent factors) then the generative model can be specified in terms of
% the likelihood and prior tensors; MDP.GA and MDP.GB, respectively. The
% controllable factors of the generative process are specified in MDP.GU.
% Specifying a generative process will automatically invoke explicit
% action; namely, the most likely policy (combination of controllable
% paths) will automatically realise predicted outcomes. I.e., the policy
% that minimises variational free energy or maximises accuracy (as opposed
% to directly implementing the path selected under the generative model).
% Explicit action is a more biomimetic, if vicarious, approach to realising
% inferred paths.
%
% This scheme is designed for any allowable policies or control variables
% specified in MDP.U. Constraints on allowable policies can limit the
% numerics or combinatorics considerably. Further, the outcome space and
% hidden states can be defined in terms of factors; corresponding to
% sensory modalities and (functionally) segregated representations,
% respectively. This means, for each factor or subset of hidden states
% there are corresponding control states that determine the transition
% probabilities. in this implementation, hidden factors are combined using
% a Kronecker tensor product to enable exact Bayesian inference using
% belief propagation (the Kronecker tensor form ensures that conditional
% dependencies among hidden factors are evaluated).
%
% In this belief propagation scheme, the next action is evaluated in terms
% of the free energy expected under all subsequent actions until some time
% horizon (specified by MDP.T). This expected free energy is accumulated
% along all allowable paths or policies (see the subroutine spm_forward);
% effectively, performing a deep tree search over future sequences of
% actions. Because actions are conditionally independent of previous
% actions, it is only necessary to update posterior beliefs over hidden
% states at the current time point (using a Bayesian belief updating) and
% then use the prior over actions (based upon expected free energy) to
% select the next action. Previous actions are inferred under the posterior
% beliefs over current states; i.e., inferred state transitions.
%
% In brief, the agent encodes beliefs about hidden states in the past
% conditioned on realised outcomes and actions. The resulting conditional
% expectations determine the (path integral) of expected free energy that
% then determines an empirical prior over the next action, from which the
% next realised action sampled
%
% If supplied with a structure array, this routine will automatically step
% through the implicit sequence of epochs (implicit in the number of
% columns of the array). If the array has multiple rows, each row will be
% treated as a separate model or agent. This enables agents to communicate
% through acting upon a common set of hidden factors, or indeed sharing the
% same outcomes.
%
% See also: spm_MDP, which uses multiple future states and a mean field
% approximation for control states - but allows for different actions at
% all times (as in control problems).
%
% See also: spm_MDP_VB_X,  which is the corresponding variational message
% passing scheme for fixed policies; i.e., ordered sequences of actions
% that are specified a priori.
%
% See also: spm_MDP_VB_XX,  which is the corresponding variational message
% passing scheme for sophisticated policy searches under the assumption
% that the generative process and model have the same structure
%__________________________________________________________________________
% Copyright (C) 2019 Wellcome Trust Centre for Neuroimaging

% Karl Friston
% $Id: spm_MDP_VB_XXX.m 8418 2023-02-27 19:17:56Z karl $


% deal with a sequence of trials
%==========================================================================

% options
%--------------------------------------------------------------------------
try, OPTIONS.B; catch, OPTIONS.B = 0; end      % backwards pass
try, OPTIONS.C; catch, OPTIONS.C = 0; end      % check sizes and labels
try, OPTIONS.D; catch, OPTIONS.D = 0; end      % final states
try, OPTIONS.N; catch, OPTIONS.N = 0; end      % neuronal responses
try, OPTIONS.P; catch, OPTIONS.P = 0; end      % graphics

% check MDP specification
%--------------------------------------------------------------------------
MDP = spm_MDP_checkX(MDP);


% handle multiple trials, ensuring parameters (and posteriors) are updated
%==========================================================================
if size(MDP,2) > 1

    % plotting options
    %----------------------------------------------------------------------
    GRAPH     = OPTIONS.P;
    OPTIONS.P = 0;

    for i = 1:size(MDP,2)                      % number of trials
        for m = 1:size(MDP,1)                  % number of agents
            if i > 1                           % if previous inversions

                % update concentration parameters
                %----------------------------------------------------------
                MDP(m,i) = spm_MDP_update(MDP(m,i),OUT(m,i - 1));

                % update initial states (postdiction)
                %----------------------------------------------------------
                if any(OPTIONS.D)
                    nD = numel(MDP(m,i).D);
                    if numel(OPTIONS.D) ~= nD
                        OPTIONS.D = ones(nD,1);
                    end
                    for f = 1:nD
                        if OPTIONS.D(f)
                            MDP(m,i).D{f} = OUT(m,i - 1).X{f}(:,end);
                        end
                    end
                end
            end
        end

        % solve this MDP (for all models synchronously)
        %------------------------------------------------------------------
        OUT(:,i) = spm_MDP_VB_XXX(MDP(:,i),OPTIONS);
        fprintf('Update %i\n',i);

        % Bayesian model reduction
        %------------------------------------------------------------------
        if isfield(OPTIONS,'BMR')
            if isfield(OPTIONS.BMR,'fun')
                bmrfun = OPTIONS.BMR.fun;
            else
                bmrfun = @(MDP,BMR) spm_MDP_VB_sleep(MDP,BMR);
            end
            for m = 1:size(MDP,1)
                OUT(m,i) = bmrfun(OUT(m,i),OPTIONS.BMR);
            end
        end

    end

    % plot summary statistics - over trials
    %----------------------------------------------------------------------
    MDP = OUT;
    if GRAPH
        if ishandle(GRAPH)
            figure(GRAPH); clf
        else
            spm_figure('GetWin','MDP'); clf
        end
        spm_MDP_VB_game(MDP(1,:))
    end
    return
end


% set up and preliminaries
%==========================================================================

% defaults
%--------------------------------------------------------------------------
try, alpha = MDP(1).alpha; catch, alpha = 512;  end % planning precision
try, beta  = MDP(1).beta ; catch, beta  = 0;    end % learning precision
try, chi   = MDP(1).chi;   catch, chi   = 512;  end % action precision
try, eta   = MDP(1).eta;   catch, eta   = 512;  end % learnability
try, N     = MDP(1).N;     catch, N     = 0;    end % depth of policy search

% initialise model-specific parameters
%==========================================================================
T     = MDP(1).T;                              % number of updates
Nm    = numel(MDP);

% Check for generative process (invoking explicit action)
%--------------------------------------------------------------------------
process = zeros(Nm,1);
for m = 1:Nm
    process(m) = spm_is_process(MDP(m));
end

% Prelimninaries and checks
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% for each model
%--------------------------------------------------------------------------
for m = 1:Nm

    % Check for generative process
    %----------------------------------------------------------------------
    if ~process(m)

        % assume generative process is the model
        %------------------------------------------------------------------
        MDP(m).GA = MDP(m).A;
        MDP(m).GB = MDP(m).B;
        MDP(m).GD = MDP(m).D;
        MDP(m).GE = MDP(m).E;
        MDP(m).GU = MDP(m).U;

        MDP(m).ID = MDP(m).id;

    end

    % number of outcomes and latent states
    %----------------------------------------------------------------------
    Ng(m) = numel(MDP(m).A);                   % number of modalities
    Nf(m) = numel(MDP(m).B);                   % number of factors
    for g = 1:Ng(m)
        No(m,g) = size(MDP(m).A{g},1);         % number of outcomes
    end
    for f = 1:Nf(m)
        Ns(m,f) = size(MDP(m).B{f},1);         % number of hidden states
        Nu(m,f) = size(MDP(m).B{f},3);         % number of hidden paths
    end

    % number of states and paths in generative process
    %----------------------------------------------------------------------
    NF(m) = numel(MDP(m).GB);                  % number of factors
    for f = 1:NF(m)
        NS(m,f) = size(MDP(m).GB{f},1);        % number of states
        NU(m,f) = size(MDP(m).GB{f},3);        % number of paths
    end

    % Check for priors over initial states and paths of generative process
    %----------------------------------------------------------------------
    if process(m)
            for f = 1:NF
            try
                if numel(MDP(m).GD{f}) ~= NS(m,f)
                MDP(m).GD{f} = spm_norm(ones(NS(m,f),1));
            end
            catch
                MDP(m).GD{f} = spm_norm(ones(NS(m,f),1));
            end
            try
                if numel(MDP(m).GE{f}) ~= NU(m,f)
                    MDP(m).GE{f} = spm_norm(ones(NU(m,f),1));
                end
            catch
                MDP(m).GE{f} = spm_norm(ones(NU(m,f),1));
            end
        end

        % Check indices of domains and co-domains
        %--------------------------------------------------------------------------
        if ~isfield(MDP(m),'ID')
            MDP(m).ID.g  = {1:Ng};
            for g = 1:Ng
                MDP(m).ID.A{g} = 1:(ndims(MDP(m).GA{g}) - 1);
            end
        end

        end
    end

    % parameters of generative model and policies
%==========================================================================
O     = cell(Nm,max(Ng),T);                   % outcomes
for m = 1:Nm

    % likelihood model (for a partially observed MDP)
    %----------------------------------------------------------------------
    for g = 1:Ng(m)

        % parameters (concentration parameters): a
        %------------------------------------------------------------------
        if isfield(MDP,'a')
            qa{m,g} = MDP(m).a{g};
        else
            qa{m,g} = MDP(m).A{g}*512;
        end

        % Dirichlet prior
        %------------------------------------------------------------------
        pa{m,g} = qa{m,g};

        % normalised likelihood
        %------------------------------------------------------------------
        A{m,g}  = spm_norm(qa{m,g});

        % prior concentration parameters and novelty (W)
        %------------------------------------------------------------------
        if isfield(MDP,'a')
            W{m,g} = spm_wnorm(qa{m,g});
        else
            W{m,g} = [];
        end

        % and ambiguity (w) (for computation of expected free energy: G)
        %------------------------------------------------------------------
        if islogical(qa{m,g})
            K{m,g} = [];
        else
            K{m,g} = spm_hnorm(qa{m,g});
    end

        % prior preferences over outcomes (concentration parameters) : C
        %------------------------------------------------------------------
        if isfield(MDP,'c')
            qc{m,g} = MDP(m).c{g};
        elseif isfield(MDP,'C')
            qc{m,g} = MDP(m).C{g}*512;
        else
            qc{m,g} = ones(No(m,g),1);
        end

        % Dirichlet prior
        %------------------------------------------------------------------
        pc{m,g} = qc{m,g};

        % prior preferences (concentration parameters) : C
        %------------------------------------------------------------------
        C{m,g}  = spm_norm(qc{m,g});

    end

    % transition probabilities (priors)
    %----------------------------------------------------------------------
    for f = 1:Nf(m)

        % parameters (concentration parameters): b
        %------------------------------------------------------------------
        if isfield(MDP,'b')
            qb{m,f} = MDP(m).b{f};
        else
            qb{m,f} = MDP(m).B{f}*512;
        end

        % Dirichlet prior
        %------------------------------------------------------------------
        pb{m,f} = qb{m,f};

        % normalised transition probabilities
        %------------------------------------------------------------------
        B{m,f}  = spm_norm(qb{m,f});

        % prior concentration parameters and novelty (I)
        %------------------------------------------------------------------
        if isfield(MDP,'b')
            I{m,f} = spm_wnorm(qb{m,f});
        else
            I{m,f} = [];
        end

        % priors over initial hidden states: concentration parameters
        %------------------------------------------------------------------
        if isfield(MDP,'d')
            qd{m,f} = MDP(m).d{f};
        elseif isfield(MDP,'D')
            qd{m,f} = MDP(m).D{f}*512;
        else
            qd{m,f} = ones(Ns(m,f),1);
        end

        % Dirichlet prior
        %------------------------------------------------------------------
        pd{m,f} = qd{m,f};

        % normalised prior probabilities
        %------------------------------------------------------------------
        D{m,f}  = spm_norm(qd{m,f});

        % priors over paths (control states): concentration parameters
        %------------------------------------------------------------------
        if isfield(MDP,'e')
            qe{m,f} = MDP(m).e{f};
        elseif isfield(MDP,'E')
            qe{m,f} = MDP(m).E{f}*512;
        else
            qe{m,f} = ones(Nu(m,f),1);
        end

        % Dirichlet prior
        %------------------------------------------------------------------
        pe{m,f} = qe{m,f};

        % normalised prior probabilities
        %------------------------------------------------------------------
        E{m,f}  = spm_norm(qe{m,f});

        % priors over final hidden states: concentration parameters
        %------------------------------------------------------------------
        if isfield(MDP,'h')
            try
            qh{m,f} = MDP(m).h{f};
            catch
                qh{m,f} = [];
            end
        elseif isfield(MDP,'H')
            try
            qh{m,f} = MDP(m).H{f}*512;
            catch
                qh{m,f} = [];
            end
        else
            qh{m,f} = [];
        end

        % Dirichlet prior
        %------------------------------------------------------------------
        ph{m,f} = qh{m,f};

        % normalised prior probabilities
        %------------------------------------------------------------------
        H{m,f}  = spm_norm(qh{m,f});

        end

    % controllable factors
    %======================================================================

    % policies (GV) - generative factors
    %----------------------------------------------------------------------
    k          = find(any(MDP(m).GU,1));
    u          = spm_combinations(NU(m,k));
    GV{m}      = zeros(size(u,1),NF(m));
    GV{m}(:,k) = u;
    Na(m)     = size(GV{m},1);                 % number of action policies

    % policies (V) - latent factors
    %----------------------------------------------------------------------
    U{m}       = any(MDP(m).U,1);
        k         = find(U{m});
        u         = spm_combinations(Nu(m,k));
        V{m}      = zeros(size(u,1),Nf(m));
        V{m}(:,k) = u;

    % replace with V if specified
    %----------------------------------------------------------------------
    if isfield(MDP(m),'V')
        V{m}  = MDP(m).V;
        U{m}  = any(MDP(m).V,1);
    end
    Np(m)     = size(V{m},1);                 % number of latent policies

    
    % initialise posterior expectations of hidden states (X) and paths (S)
    %======================================================================
    for f = 1:Nf(m)
        for t = 1:T
            Q{m,f,t} = D{m,f};
        end
        X{m,f} = repmat(D{m,f},1,T);
        S{m,f} = repmat(E{m,f},1,T);

        if OPTIONS.N
            sn{m,f} = zeros(Ns(m,f),T,T) + 1/Ns(m,f);
        end
    end

    % initialise posteriors over control states
    %----------------------------------------------------------------------
    for f = 1:Nf(m)
        for t = 1:T
            P{m,f,t} = E{m,f};
        end
    end

    % if states have not been specified, set to 0
    %----------------------------------------------------------------------
    k        = zeros(NF(m),T);
    try
        i    = find(MDP(m).s);
        k(i) = MDP(m).s(i);
    end
    MDP(m).s = k;

    % if paths have not been specified, set to 0
    %----------------------------------------------------------------------
    k        = zeros(NF(m),T);
    try
        i    = find(MDP(m).u);
        k(i) = MDP(m).u(i);
    end
    MDP(m).u = k;

    % if outcomes have not been specified set to 0
    %======================================================================
    k        = zeros(Ng(m),T);
    try
        i    = find(MDP(m).o);
        k(i) = MDP(m).o(i);
    end
    MDP(m).o = k;

    % if outcomes are specified probabilistically
    %----------------------------------------------------------------------
    if isfield(MDP(m),'O')
    for g  = 1:Ng(m)
        for t = 1:T
            try
                % Probabilistic outcomes
                    %-------------------------------------------------------
                O{m,g,t}      = MDP(m).O{g,t};

                % Overwrite deterministic outcomes
                    %------------------------------------------------------
                    MDP(m).o(g,t) = spm_sample(O{m,g,t});

            catch
                O{m,g,t}      = [];
            end
        end
    end
    end

    % domains (id)
    %----------------------------------------------------------------------
    id{m} = MDP(m).id;
    ID{m} = MDP(m).ID;

    % predictable outcomes
    %----------------------------------------------------------------------
    if ~isfield(ID{m},'control')
        ID{m}.control = 1:Ng(m);
    end

end % end model (m)


% ensure any outcome generating agent is updated first
%--------------------------------------------------------------------------
N       = min(N,T);                          % depth of policy search
[M,MDP] = spm_MDP_get_M(MDP,T,Ng);           % order of model updating

% pre-allocation of cell arrays
%--------------------------------------------------------------------------
BP      = cell(Nm,Nf(m),Np(m));
IP      = cell(Nm,Nf(m),Np(m));



% Bayesian model inversion
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% belief updating over successive time points
%==========================================================================
for t = 1:T

    % generate hidden states and controls for each agent or model
    %======================================================================
    for m = M(t,:)

        % explicit action MDP(m).u to realise initial state MDP(m).s
        %==================================================================
        if process(m) && t == 1 && isfield(MDP(m),'s0')

            % prior over control outcomes
            %--------------------------------------------------------------
            qo    = cell(Ng(m),1);
            for g = ID{m}.control

                % domain of A{g}
                %----------------------------------------------------------
                j     = spm_get_edges(id{m},g,D(m,:));
                qo{g} = spm_dot(A{m,g},Q(m,j,t));

            end

            % find actions that minimise prediction error
            %--------------------------------------------------------------
            l     = any(GV{m},1);
            F     = zeros(Na(m),1);
            qs    = cell(NF(m),Na(m));
            for k = 1:Na(m)

                % predicted states under this policy
                %----------------------------------------------------------
                u     = MDP(m).u0;
                u(l)  = GV{m}(k,l);
                for f = 1:NF(m)
                    qs{f,k} = MDP(m).GB{f}(:,MDP(m).s0(f),u(f));
                end

                % free energy or prediction error (i.e., inaccuracy)
                %----------------------------------------------------------
                for g = ID{m}.control
                    j    = spm_get_edges(ID{m},g,qs(:,k));
                    po   = spm_dot(MDP(m).GA{g},qs(j,k));
                    F(k) = F(k) + qo{g}'*spm_log(po);
                end

            end

            % action
            %--------------------------------------------------------------
            k             = spm_sample(spm_softmax(chi*F));
            MDP(m).u(:,t) = MDP(m).u0;
            MDP(m).u(l,t) = GV{m}(k,l)';

            % and realised initial state
            %--------------------------------------------------------------
            for f = 1:NF(m)
                MDP(m).s(f,t) = spm_sample(qs{f,k});
            end

        end

        % initialise and propagate control state (path) MDP(m).u
        %==================================================================
        for f = 1:NF(m)
            if ~MDP(m).u(f,t)
                if t > 1

                    % previous path
                    %------------------------------------------------------
                    MDP(m).u(f,t) = MDP(m).u(f,t - 1);

                    else

                    % otherwise sample a path
                    %------------------------------------------------------
                    pu            = spm_norm(MDP(m).GE{f});
                    MDP(m).u(f,t) = spm_sample(pu);

                end
            end
        end

        % action generating outcomes (for controllable factors)
        %==================================================================
        if t > 1

            % implicit action
            %--------------------------------------------------------------
            k     = spm_sample(Pu);
            for f = 1:Nf(m)

                if U{m}(f)

                    % prior postdictive density (paths)
                    %------------------------------------------------------
                    u               = V{m}(k,f);
                    P{m,f,t - 1}(:)   = 0;
                    P{m,f,t - 1}(u)   = 1;

                    % selected action
                    %------------------------------------------------------
                    if ~process(m)
                        MDP(m).u(f,t - 1) = u;
                    end

                end

                % prior predictive density over hidden states
                %==========================================================
                Q{m,f,t} = spm_dot(B{m,f},P(m,f,t - 1))*Q{m,f,t - 1};

            end


            % explicit action
            %--------------------------------------------------------------
            if process(m)

                % predicted outcomes
                %----------------------------------------------------------
                qo    = cell(Ng(m),1);
                for g = ID{m}.control

                    % domain of A{g}
                    %------------------------------------------------------
                    j     = spm_get_edges(id{m},g,Q(m,:,t));
                    qo{g} = spm_dot(A{m,g},Q(m,j,t));

                end

                % find actions that minimise prediction error
                %----------------------------------------------------------
                l     = any(GV{m},1);
                F     = zeros(Na(m),1);
                qs    = cell(NF(m),1);
                for k = 1:Na(m)

                    % predicted states under this policy
                    %------------------------------------------------------
                    u     = MDP(m).u(:,t - 1);
                    u(l)  = GV{m}(k,l);
                    for f = 1:NF(m)
                        qs{f} = MDP(m).GB{f}(:,MDP(m).s(f,t - 1),u(f));
                    end

                    % free energy or prediction error (i.e., inaccuracy)
                    %------------------------------------------------------
                    F(k)  = 0;
                    for g = ID{m}.control
                        j     = spm_get_edges(ID{m},g,qs);
                        po    = spm_dot(MDP(m).GA{g},qs(j));
                        F(k)  = F(k) + qo{g}'*spm_log(po);
                    end

                end

                % most likely control state
                %----------------------------------------------------------
                k                 = spm_sample(spm_softmax(chi*F));
                MDP(m).u(l,t - 1) = GV{m}(k,l)';

                end

        end % end generating paths or actions


        % sample state if not specified
        %==================================================================
        for f = 1:NF(m)
            if ~MDP(m).s(f,t)

                if t > 1

                % the next state is generated by state transititions
                %----------------------------------------------------------
                    ps = MDP(m).GB{f}(:,MDP(m).s(f,t - 1),MDP(m).u(f,t - 1));

                else

                    % unless it is the initial state
                    %------------------------------------------------------
                    ps = spm_norm(MDP(m).GD{f});

                end

                MDP(m).s(f,t) = spm_sample(ps);

            end

        end % end generating states

    end % end generating over models


    % share states if specified in MDP.m
    %----------------------------------------------------------------------
    for m = M(t,:)
        for f = 1:NF(m)
            if isfield(MDP(m),'m')
                n = MDP(m).m(f);
                if n
                    MDP(m).s(f,t) = MDP(n).s(f,t);
                end
            end
        end
    end

    % generate outcomes O{m,g,t} for each agent or model
    %======================================================================
    for m = M(t,:)

        % selected outcome modalities
        %------------------------------------------------------------------
        ig{m} = spm_get_g(id{m},t);

        % generate outcome, if not specified
        %------------------------------------------------------------------
        for g = 1:Ng(m)

            % domain and codomain of A{g}
            %--------------------------------------------------------------
            [j,i] = spm_get_edges(ID{m},g,MDP(m).s(:,t));
            for o = i

            % if outcome is not specified
                %----------------------------------------------------------
                if ~MDP(m).o(o,t)

                % outcome is generated by model n
                    %------------------------------------------------------
                    if MDP(m).n(o,t) > 0

                        n    = MDP(m).n(o,t);
                    if n == m

                        % outcome that maximises accuracy (i.e. ELBO)
                            %----------------------------------------------
                            F             = spm_log(spm_dot(A{m,g},Q(m,j,t)));
                            O{m,o,t}      = spm_softmax(F*512);
                            MDP(m).o(o,t) = spm_sample(O{m,o,t});

                    else

                        % outcome from model n (previously sampled)
                            %----------------------------------------------
                            O{m,o,t}      = O{n,o,t};
                            MDP(m).o(o,t) = MDP(n).o(o,t);

                    end

                    elseif MDP(m).n(o,t) < 0

                    % outcome is generated by all models or agents
                        %--------------------------------------------------
                        Fm{o,m}       = spm_log(spm_dot(A{m,g},Q(m,j,t)));

                else

                        % or sample from likelihood, given hidden state
                        %==================================================
                            ind       = num2cell(MDP(m).s(j,t));
                        if process(m)
                            if isa(MDP(m).GA{g},'function_handle')
                                O{m,o,t} = MDP(m).GA{g}([ind{:}]);
                            else
                            O{m,o,t}  = MDP(m).GA{g}(:,ind{:});
                            end
                        else
                        O{m,o,t}      = MDP(m).A{g}(:,ind{:});
                        end

                        MDP(m).o(o,t) = spm_sample(O{m,o,t});

                end

            else 

                % use sampled outcomes if no probabilistic specification
                    %------------------------------------------------------
                    if isempty(O{m,o,t})
                        O{m,o,t} = full(sparse(MDP(m).o(o,t),1,1,No(m,o),1));
                    end

                end

            end % end children of likelihood mapping

        end % end generate outomes O{m,g,t} from states

    end % end models


    % shared probabilistic outcomes O{m,g,t} and realizatons MDP(m).o(g,t)
    %======================================================================
    for m = M(t,:)
        for g = 1:Ng(m)

            % share outcomes if specified in MDP.m
            %--------------------------------------------------------------
            if MDP(m).n(g,t) < 0
                j = 1:Nm; j(m) = []; % sensory attenuation
         
                F             = sum([Fm{g,j}],2);
                O{m,g,t}      = spm_softmax(F);
                po            = spm_softmax(F*512);
                MDP(m).o(g,t)  = spm_sample(po);

            end
        end
    end


    % or generate outcomes O{m,g,t} from a subordinate MDP
    %======================================================================
    for m = M(t,:)

        if isfield(MDP,'MDP')

            % get child and initialise record of outcomes (Q)
            %--------------------------------------------------------------
                        mdp = MDP(m).MDP(1);

            % priors over states and paths of children
            %==============================================================

                % empirical priors over initial states: 
            %--------------------------------------------------------------
            for f = 1:numel(mdp.id.D)
                g        = mdp.id.D{f};
                j        = spm_get_edges(id{m},g,Q(m,:,t));
                mdp.D{f} = spm_dot(A{m,g},Q(m,j,t));
                    end

                % empirical priors over paths: 
            %--------------------------------------------------------------
            for f = 1:numel(mdp.id.E)
                g        = mdp.id.E{f};
                j        = spm_get_edges(id{m},g,Q(m,:,t));
                mdp.E{f} = spm_dot(A{m,g},Q(m,j,t));
            end

            % states and paths of generative process
            %==============================================================
            if ~spm_is_process(mdp)

                % states of generative process
                %----------------------------------------------------------
                for f = 1:numel(mdp.id.D)
                    g      = mdp.id.D{f};
                    j      = spm_get_edges(id{m},g,MDP(m).s(:,t));
                    ind    = num2cell(MDP(m).s(j,t));
                    if isa(MDP(m).GA{g},'function_handle')
                        po = MDP(m).GA{g}([ind{:}]);
                    else
                        po = MDP(m).GA{g}(:,ind{:});
                    end
                    mdp.s(f,1) = spm_sample(po);
                end

                % paths of generative process
                %----------------------------------------------------------
                for f = 1:numel(mdp.id.E)
                    g      = mdp.id.E{f};
                    j      = spm_get_edges(id{m},g,MDP(m).s(:,t));
                    ind    = num2cell(MDP(m).s(j,t));
                    if isa(MDP(m).GA{g},'function_handle')
                        po = MDP(m).GA{g}([ind{:}]);
                    else
                        po = MDP(m).GA{g}(:,ind{:});
                    end
                    mdp.u(f,1) = spm_sample(po);
                end
                end

            % previous states and outcomes (s0,u0,& O) for this level
            %==============================================================
            if isfield(MDP(m),'Q')
                mdp.Q  = MDP(m).Q;
                if isfield(mdp,'a' ), mdp.a = mdp.Q.a{mdp.L}; end
                if isfield(mdp,'b' ), mdp.b = mdp.Q.b{mdp.L}; end
                mdp.s0 = mdp.Q.s0{mdp.L};
                mdp.u0 = mdp.Q.u0{mdp.L};
            end

            % if outcomes (stimuli) are supplied
            %--------------------------------------------------------------
            if isfield(mdp,'S')

                % time points for this iteration
                %----------------------------------------------------------
                if isfield(mdp,'Q')
                    seg = (1:mdp.T) + size(mdp.Q.O{mdp.L},2);
                else
                    seg = (1:mdp.T);
                end

                % transcribe stimuli to outcomes if specified
                %----------------------------------------------------------
                try 
                    mdp.O = mdp.S(:,seg);
                end
            end

            % infer hidden states at lower level (outcomes at this level)
            %==============================================================
            mdp   = spm_MDP_VB_XXX(mdp);

            % posteriors over states and paths of children
            %--------------------------------------------------------------
            for f = 1:numel(mdp.id.D)

                % posterior over initial states
                %----------------------------------------------------------
                g        = mdp.id.D{f};
                O{m,g,t} = mdp.X{f}(:,1);

            end

            for f = 1:numel(mdp.id.E)

                % posterior over paths
                %----------------------------------------------------------
                g        = mdp.id.E{f};
                O{m,g,t} = mdp.P{f}(:,end);

            end

            % final states  (s0,u0) and parameters (a,b)
            %==============================================================
            if isfield(mdp,'a' ), mdp.Q.a{mdp.L} = mdp.a; end
            if isfield(mdp,'b' ), mdp.Q.b{mdp.L} = mdp.b; end
            mdp.Q.s0{mdp.L} = mdp.s(:,end);
            mdp.Q.u0{mdp.L} = mdp.u(:,end);

            % and record outcomes (s,u,Y,O,o)
            %--------------------------------------------------------------
            try
                mdp.Q.s{mdp.L} = [mdp.Q.s{mdp.L} mdp.s];
                mdp.Q.u{mdp.L} = [mdp.Q.u{mdp.L} mdp.u];
                mdp.Q.Y{mdp.L} = [mdp.Q.Y{mdp.L} mdp.Y];
                mdp.Q.O{mdp.L} = [mdp.Q.O{mdp.L} mdp.O];
                mdp.Q.o{mdp.L} = [mdp.Q.o{mdp.L} mdp.o];
                mdp.Q.E{mdp.L} = [mdp.Q.E{mdp.L} mdp.F];
                mdp.Q.F        =  mdp.Q.F + sum(mdp.F);
            catch
                mdp.Q.s{mdp.L} = mdp.s;
                mdp.Q.u{mdp.L} = mdp.u;
                mdp.Q.Y{mdp.L} = mdp.Y;
                mdp.Q.O{mdp.L} = mdp.O;
                mdp.Q.o{mdp.L} = mdp.o;
                mdp.Q.E{mdp.L} = mdp.F;
                mdp.Q.F        = sum(mdp.F);
            end
            MDP(m).Q = mdp.Q;

        end % end of hierarchical mode

    end % end generating outcomes O for all models


    % Bayesian belief updating, given O: hidden states (Q) and paths (P)
    %======================================================================
    for m = M(t,:)

        % belief propagation (BP) under policy k
        %------------------------------------------------------------------
        for f = 1:Nf(m)
            for k = 1:Np(m)
                if V{m}(k,f)

                    % transitions and novelty for this policy
                    %------------------------------------------------------
                    BP{m,f,k} = B{m,f}(:,:,V{m}(k,f));
                    if numel(I{m,f})
                        IP{m,f,k} = I{m,f}(:,:,V{m}(k,f));
                else
                        IP{m,f,k} = [];
                    end

                else

                    % transitions and novelty for this policy
                    %------------------------------------------------------
                    if isscalar(P{m,f,t})
                        BP{m,f,k} = B{m,f};
                    else
                    BP{m,f,k} = spm_dot(B{m,f},P(m,f,t));
                    end

                    if numel(I{m,f})
                        IP{m,f,k} = spm_dot(I{m,f},P(m,f,t));
                    else
                        IP{m,f,k} = [];
                    end

                end
            end
        end


        % posterior over hidden states (Q) and expected free energy (G)
        %==================================================================
        [G,Q,F,id] = spm_forwards(O,Q,A,BP,C,H,K,W,IP,t,T,min(T,t + N),m,id);

        % augment with prior probability over paths
        %------------------------------------------------------------------
        if t == 1
        for k = 1:Np(m)
            LE     = 0;
            for f  = find(U{m})
                LE = LE + spm_log(E{m,f}(V{m}(k,f)));
            end
            G(k)   = G(k) + LE;
        end
        end

        % prior beliefs about policies (R) and precision (w)
        %------------------------------------------------------------------
        R{m}(:,t)  = spm_softmax(G);
        w{m}(t)    = R{m}(:,t)'*spm_log(R{m}(:,t));
        v{m}(t)    = R{m}(:,t)'*G;


        % posterior over previous path (P)
        %==================================================================
        Z  = 0;
        if t > 1
            for f = 1:Nf(m)

                % log likelihood of paths
                %----------------------------------------------------------
                LL = spm_dot(spm_dot(B{m,f},Q{m,f,t}),Q{m,f,t - 1});
                LL = spm_log(LL);

                % prior over previous path
                %----------------------------------------------------------
                LP = spm_log(P{m,f,t - 1});

                % posterior over previous path = prior over current path
                %----------------------------------------------------------
                P{m,f,t - 1} = spm_softmax(LL + LP);

                % (negative) complexity of paths (or control states)
                %----------------------------------------------------------
                Z  = Z + P{m,f,t - 1}'*(LL + LP - spm_log(P{m,f,t - 1}));

            end

        end % end previous control states


        % prior over current path or control state (P)
        %==================================================================

        % prior over policy (i.e.,action combination)
        %------------------------------------------------------------------
        Pu    = spm_softmax(alpha*G);
        for f = 1:Nf(m)
            
            if U{m}(f)

                % prior over control state
                %----------------------------------------------------------
                for u = 1:Nu(m,f)
                    P{m,f,t}(u) = Pu'*(V{m}(:,f) == u);
                end

            else

                % or unchanging path
                %----------------------------------------------------------
                if t > 1
                    P{m,f,t} = P{m,f,t - 1};
                end
            end

        end % end current control states


        % active (likelihood) learning
        %==================================================================

        % mapping from hidden states to outcomes: a
        %------------------------------------------------------------------
        if isfield(MDP(m),'a')

            for g = ig{m}

                % domain of A{g}
                %----------------------------------------------------------
                [j,k] = spm_get_edges(id{m},g,Q(m,:,t));
                if numel(k)
                    
                da    = 0;
                for i = k
                    da = da + spm_cross(O{m,i,t},Q{m,j,t});
                end
                da(~qa{m,g}) = 0;
                    da      = reshape(da,size(qa{m,g}));

                % update likelihood Dirichlet parameters
                    %------------------------------------------------------
                qa{m,g} = qa{m,g} + da;
                A{m,g}  = spm_norm(qa{m,g});

                % prior concentration parameters and novelty (W)
                    %------------------------------------------------------
                W{m,g} = spm_wnorm(qa{m,g});

                % and ambiguity (w)
                    %------------------------------------------------------
                K{m,g} = spm_hnorm(qa{m,g});

            end
        end
        end

        % mapping among hidden states: b
        %------------------------------------------------------------------
        if isfield(MDP(m),'b') && t > 1  %%%% && any(U{m})
            for f = 1:Nf(m)

                % domain of B{f}
                %----------------------------------------------------------
                db = spm_cross(spm_cross(Q{m,f,t},Q{m,f,t - 1}),P{m,f,t - 1});
                db(~qb{m,f}) = 0;

                % update prior Dirichlet parameters
                %----------------------------------------------------------
                qb{m,f} = qb{m,f} + db;
                B{m,f}  = spm_norm(qb{m,f});

                % prior concentration parameters and novelty (W)
                %----------------------------------------------------------
                I{m,f} = spm_wnorm(qb{m,f});

        end
        end


        % (ELBO) free energy: states, policies and paths
        %------------------------------------------------------------------
        MDP(m).F(t) = F;
        MDP(m).G{t} = G;
        MDP(m).Z(t) = Z;

        % save marginal posteriors over hidden states: c.f., working memory
        %==================================================================
        if OPTIONS.N
            for f = 1:Nf(m)
                for i = 1:T
                    sn{m,f}(:,i,t) = Q{m,f,i};
                end
            end
        end

    end % end of loop over models (agents)

    % terminate evidence accumulation
    %----------------------------------------------------------------------
    if t == T
        for m = 1:size(MDP,1)
            MDP(m).o  = MDP(m).o(:,1:T);        % outcomes at 1,...,T
            MDP(m).s  = MDP(m).s(:,1:T);        % states   at 1,...,T
            MDP(m).u  = MDP(m).u(:,1:T);        % control  at 1,...,T - 1
        end
    end

end % end of loop over time


% accumulate Dirichlet parameters and prepare outputs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% loop over models
%--------------------------------------------------------------------------
for m = 1:size(MDP,1)

    % Smoothing or backwards pass: replay
    %======================================================================
    if OPTIONS.B

    % Smoothing of unchanging control states
        %------------------------------------------------------------------
    for f = 1:Nf(m)
        if ~U{m}(f)
            for t = 1:T
                P{m,f,t} = P{m,f,T};
            end
        end
    end

        % update posteriors
        %------------------------------------------------------------------
        [Q,P,qa,qb,F]  = spm_backwards(O,P,Q,D,E,pa,pb,U,m,id);

        % update free energy
        %------------------------------------------------------------------
        MDP(m).F = F;
    end

    % learning - accumulate concentration parameters
    %======================================================================

        % likelihood mapping from hidden states to outcomes: a
    %----------------------------------------------------------------------
        if isfield(MDP(m),'a')

        for g = 1:Ng(m)

            % active learning (based on expected free energy)
            %--------------------------------------------------------------
            if beta
                Fa(1,1) = spm_MDP_MI(pa{m,g},C{m,g},H(m,:));
                Fa(2,1) = spm_MDP_MI(qa{m,g},C{m,g},H(m,:));
            Pa          = spm_softmax(beta*Fa);
            else
                Pa      = [0,1];
            end

            MDP(m).a{g} = (Pa(1)*pa{m,g} + Pa(2)*qa{m,g})*eta/(eta + Pa(2));

            end
        end

        % mapping from hidden states to hidden states: b(u)
    %----------------------------------------------------------------------
    if isfield(MDP,'b')
            for f = 1:Nf(m)

            % active learning (based on expected free energy)
            %--------------------------------------------------------------
            if beta
                Fa(1,1) = spm_MDP_MI(pb{m,f},H{m,f});
                Fa(2,1) = spm_MDP_MI(qb{m,f},H{m,f});
                Pa          = spm_softmax(beta*Fa);
            else
                Pa      = [0,1];
        end

            MDP(m).b{f} = (Pa(1)*pb{m,f} + Pa(2)*qb{m,f})*eta/(eta + Pa(2));

        end
    end

    % accumulation of prior preferences: (c)
    %----------------------------------------------------------------------
    if isfield(MDP,'c')
        for g  = ig{m}
            dc = O{m,g,end};
            dc = dc.*(pc{m,g} > 0);
            MDP(m).c{g} = (pc{m,g} + dc)*eta/(eta + 1);
        end
    end

    % initial hidden states:
    %----------------------------------------------------------------------
    if isfield(MDP,'d')
        for f = 1:Nf(m)
            dd = Q{m,f,1};
            dd = dd.*(pd{m,f} > 0);
            MDP(m).d{f} = (pd{m,f} + dd)*eta/(eta + 1);
        end
    end

    % initial hidden paths:
    %----------------------------------------------------------------------
    if isfield(MDP,'e')
        for f = 1:Nf(m)
            de = P{m,f,1};
            de = de.*(pe{m,f} > 0);
            MDP(m).e{f} = (pe{m,f} + de)*eta/(eta + 1);
        end
    end


    % (negative) free energy of parameters (complexity): outcome specific
    %======================================================================
    for g = 1:Ng(m)
        if isfield(MDP,'a')
            MDP(m).Fa(g) = - spm_KL_dir(MDP(m).a{g},pa{m,g});
        end
        if isfield(MDP,'c')
            MDP(m).Fc(f) = - spm_KL_dir(MDP(m).c{g},pc{m,g});
        end
    end

    % (negative) free energy of parameters: state specific
    %----------------------------------------------------------------------
    for f = 1:Nf(m)
        if isfield(MDP,'b')
            MDP(m).Fb(f) = - spm_KL_dir(MDP(m).b{f},pb{m,f});
        end
        if isfield(MDP,'d')
            MDP(m).Fd(f) = - spm_KL_dir(MDP(m).d{f},pd{m,f});
        end
        if isfield(MDP,'e')
            MDP(m).Fe(f) = - spm_KL_dir(MDP(m).e{f},pe{m,f});
        end
    end

    % posterior predictive density Y{g,t}
    %======================================================================
    for g = 1:Ng(m)
        for t = 1:T
            [j,i]         = spm_get_edges(id{m},g,Q(m,:,t));
            for o = i
                MDP(m).Y{o,t} = spm_dot(A{m,g},Q(m,j,t));
            end
            MDP(m).j{g,t} = j;
            MDP(m).i{g,t} = i;
        end
    end

    % reorganise posteriors for saving
    %======================================================================

    % states and paths
    %----------------------------------------------------------------------
    for t = 1:T
        for f = 1:Nf(m)
            X{m,f}(:,t) = Q{m,f,t};
            S{m,f}(:,t) = P{m,f,t};
        end
    end


    % simulated electrophysiological responses
    %======================================================================
    if OPTIONS.N

        % initialise simulated neuronal respsonses
        %------------------------------------------------------------------
        n     = 16;
        for f = 1:Nf(m)
            xn{m,f} = zeros(n,Ns(m,f),T,T);
        end

        % simulated dopamine (or cholinergic) responses: assuming a
        % monoexponential kernel
        %------------------------------------------------------------------
        h     = exp(-(0:(n - 1))/2);
        h     = h/sum(h);
        wn{m} = kron(w{m},ones(1,n));
        wn{m} = conv(wn{m},[spm_zeros(h) h],'same');
        dn{m} = gradient(wn{m}(:));


        % Belief updating about hidden states: assuming a kernel or impulse
        % response function with a cumulative gamma distribution
        %------------------------------------------------------------------
        h     = spm_Gcdf(0:(n - 1),n/4,1);
        for f = 1:Nf(m)
            for i = 1:Ns(m,f)
                for j = 1:T
                    for k = 1:T
                        if k == 1
                            h0 = 1/Ns(m,f);
                        else
                            h0 = sn{m,f}(i,j,k - 1);
                        end
                        ht     = sn{m,f}(i,j,k);
                        xn{m,f}(:,i,j,k) = h*(ht - h0) + h0;
                    end
                end
            end
        end

        % sum to one contraint
        %------------------------------------------------------------------
        for i = 1:n
            for j = 1:T
                for k = 1:T
                    xn{m,f}(i,:,j,k) = spm_norm(xn{m,f}(i,:,j,k)');
                end
            end
        end

        % belief updating about policies
        %------------------------------------------------------------------
        u0    = spm_softmax(ones(Np(m),1));
        for k = 1:Np(m)
            for t = 1:(T - 1)
                if t == 1
                    h0 = u0(k);
                else
                    h0 = R{m}(k,t - 1);
                end
                ht         = R{m}(k,t);
                j          = (1:n) + (t - 1)*n;
                un{m}(k,j) = (h*(ht - h0) + h0);
            end
        end

    end % if neural responses


    % assemble results and place in NDP structure
    %======================================================================
    MDP(m).T  = T;            % number of outcomes
    MDP(m).U  = V{m};         % policies (combinations of controlled paths)
    MDP(m).R  = R{m};         % conditional expectations over policies
    MDP(m).X  = X(m,:);       % conditional expectations over states
    MDP(m).P  = S(m,:);       % conditional expectations over paths
    MDP(m).O  = O(m,:,:);     % outcomes
    MDP(m).v  = v{m};         % expected free energy  over policies
    MDP(m).w  = w{m};         % precision of beliefs about policies

    MDP(m).O  = shiftdim(MDP(m).O,1);
    MDP(m).P  = shiftdim(MDP(m).P,1);

    MDP(m).id = id{m};        % indices or domain identifiers

    if OPTIONS.N

        % neuronal responses
        %----------------------------------------------------------------------
        MDP(m).xn = xn(m,:);  % simulated neuronal encoding of states
        MDP(m).un = un{m};    % simulated neuronal encoding of policies
        MDP(m).wn = wn{m};    % simulated neuronal encoding of precision
        MDP(m).dn = dn{m};    % simulated dopamine responses (phasic)

    end

end % end loop over models (m)


% plot
%==========================================================================
if OPTIONS.P
    if ishandle(OPTIONS.P)
        figure(OPTIONS.P); clf
    else
        spm_figure('GetWin','MDP'); clf
    end
    spm_MDP_VB_trial(MDP(1))
end


% auxillary functions
%==========================================================================
function [G,P,F,id] = spm_forwards(O,P,A,B,C,H,K,W,I,t,T,N,m,id)
% deep tree search over policies or paths
%--------------------------------------------------------------------------
% FORMAT [G,Q,F] = spm_forwards(O,P,A,B,C,H,K,W,I,t,T,N,m)
% O{m,g,t} - cell array of outcome probabilities for modality g
% P{m,f,t} - cell array of priors over states
% A{m,g}   - likelihood mappings from hidden states
% B{m,f,k} - belief propagators (policy-dependent probability transitions)
% C{m,g}   - priors over outcomes (cost or constraint)
% H{m,f}   - priors over final states
% K{m,g}   - likelihood ambiguity
% W{m,g}   - likelihood novelty
% I{m,f,k} - transition prior novelty
%
% t        - current time point
% T        - time horizon
% N        - policy horizon
% m        - model or agent to update
% id       - domains
%
% G(k,1)   - expected free energy over k policies
% Q{m,f,t} - posterior over states
% F        - variational free energy (negative or ELBO)
%
%  This subroutine performs a deep tree search over sequences of actions to
%  evaluate the expected free energy over policies or paths. Crucially, it
%  only searches likely policies under likely hidden states in the future.
%  This search is sophisticated; in the sense that posterior beliefs are
%  updated on the basis of future outcomes to evaluate the free energy
%  under each outcome. The resulting  average is then accumulated to
%  furnish a path integral of expected free energy for the next action.
%  This routine operates recursively by updating predictive posteriors over
%  hidden states and their most likely outcomes.
%__________________________________________________________________________


% Posterior over hidden states based on likelihood (A) and priors (P)
%==========================================================================
Ni       = numel(id{m}.g);                  % number of covert policies
Nk       = size(B,3);                       % number of overt policies
Nf       = size(B,2);                       % number of factors
G        = zeros(Nk,Ni);                    % log priors over policies

% variational (Bayesian) belief updating and free energy (ELBO)
%--------------------------------------------------------------------------
[Q,F]    = spm_VBX(O(m,:,t),P(m,:,t),A(m,:),id{m});
P(m,:,t) = Q;

% next covert policy
%--------------------------------------------------------------------------
if isfield(id{m},'ig')
    id{m}.ig(t + 1) = id{m}.ig(t);
end

% terminate search at time horizon, or if only one plausible policy
%--------------------------------------------------------------------------
if t > T || numel(G) == 1, return, end

% Constraints on next state (inductive inference)
%==========================================================================
[R,r] = spm_induction(A(m,:),B(m,:,:),C(m,:),H(m,:),P(m,:,t),(T - t),id{m});

if isvector(R)
    R = R(:)';
end

% Expected free energy of subsequent action
%==========================================================================
Q     = cell(Nf,Nk);                        % predictive posterior
for k = 1:Nk                                % search over policies

    % (negative) expected free energy
    %----------------------------------------------------------------------
    for f = 1:Nf

        % predictive posterior
        %------------------------------------------------------------------
        Q{f,k} = B{m,f,k}*P{m,f,t};

        % G(k): risk over latent states
        %------------------------------------------------------------------
        if numel(H{m,f})
            G(k,:) = G(k,:) - Q{f,k}'*(spm_log(Q{f,k}) - spm_log(H{m,f}));
        end

        % expected information gain (transition novelty) (B)
        %------------------------------------------------------------------
        if numel(I{m,f,k})
            G(k,:) = G(k,:) + P{m,f,t}'*I{m,f,k}*Q{f,k};
        end

    end

    % inductive constraints over states
    %----------------------------------------------------------------------
    if numel(R)
        G(k,:) = G(k,:) + spm_dot(R,Q(r,k));
    end

    % and outcomes
    %----------------------------------------------------------------------
    No    = zeros(1,Ni);                     % log number of outcomes
    for i = 1:Ni                             % covert policies

        for ig = id{m}.g{i}                  % for selected modalities

            % (state-dependent) domain of A{g}
            %--------------------------------------------------------------
            [j,gg] = spm_get_edges(id{m},ig,Q(:,k));

            for g = gg

        % predictive posterior and prior over outcomes
                %----------------------------------------------------------
        qo   = spm_dot(A{m,g},Q(j,k));

                % number of outomes
                %----------------------------------------------------------
                No(i) = No(i) + spm_log(numel(qo));

        % G(k): risk over outomes
                %----------------------------------------------------------
                G(k,i) = G(k,i) - qo'*(spm_log(qo) - spm_log(C{m,g}));

        % G(k): ambiguity
                %----------------------------------------------------------
                if numel(K{m,g})
                G(k,i) = G(k,i) + spm_dot(K{m,g},Q(j,k));
        end

            % expected information gain (likelihood novelty) (A)
                %----------------------------------------------------------
                if numel(W{m,g})
                G(k,i) = G(k,i) + qo'*spm_dot(W{m,g},Q(j,k));
        end
            end
    end
end
end

% Covert policy (attentional selection of likelihood modalities)
%--------------------------------------------------------------------------
G     = plus(G,No);
if isfield(id{m},'ig')

    % max expected free energy over outcome partition
    %----------------------------------------------------------------------
    [~,j] = max(max(G,[],1));
G     = G(:,j);

    % update next covert policy
    %----------------------------------------------------------------------
id{m}.ig(t + 1) = j;

else
    % sum expected free energy over outcome partition 
    %----------------------------------------------------------------------
    G     = sum(G,2);
    j     = 1;
end

% deep (recursive) search over action sequences ( i.e., paths)
%==========================================================================
if t < N

    % probability over action (terminating search at a suitable threshold)
    %----------------------------------------------------------------------
    ig    = id{m}.g{j};                          % modalities
    u     = spm_softmax(G);                      % predictive prior
    k     = u > max(u)/16;                       % plausible states
    u(~k) = 0;
    G(~k) = max(G) - 512;

    % accumulate the path integral of expected free energy
    %----------------------------------------------------------------------
    for k = 1:Nk                                 % search over policies
        if u(k)                                  % and plausible states

            % get hidden factors for sampled modalities
            %--------------------------------------------------------------
            j     = [];
            for g = ig
                j = unique([j,spm_get_edges(id{m},g,Q(:,k))]);
            end

            %  find plausible combinations of hidden states
            %--------------------------------------------------------------
            s     = cell(size(j));
            S     = cell(size(j));
            n     = cell(size(j));
            for f = 1:numel(j)
                s{f} = find(Q{j(f),k} > exp(-8));
                S{f} = Q{j(f),k}(s{f});
                n{f} = numel(s{f});
            end

            % restrict tree search to (4) most likely combinations
            %--------------------------------------------------------------
            q     = spm_cross(S);
            q     = reshape(q,n{:},1);
            [~,i] = sort(q(:),'descend');
            i     = i(4 + 1:end);
            q(i)  = 0;
            q     = q/sum(q,'all');

            % Evaluate expected free energy for these hidden states
            %--------------------------------------------------------------
            EFE   = zeros(size(q));
            for i = 1:numel(q)
                
                if q(i)

                    % indices of i-th combination of hidden states
                    %------------------------------------------------------
                    ind  = [spm_index(size(q),i), ones(1,numel(j))];
                    fi    = zeros(1,Nf);
                    for f = 1:numel(j)
                        fi(j(f)) = s{f}(ind(f));
                    end

                    % outcomes under this hidden state
                    %------------------------------------------------------
                    for g = ig
                        [f,gg] = spm_get_edges(id{m},g,Q(:,k));
                        ind    = num2cell(fi(f));
                        for o = gg
                            O{m,o,t + 1} = A{m,g}(:,ind{:});
                end
                    end

                    % prior over subsequent states under this action 
                    %------------------------------------------------------
                P(m,:,t + 1) = Q(:,k);
                E      = spm_forwards(O,P,A,B,C,H,K,W,I,t + 1,T,N,m,id);

                    % expected free energy marginalised over action
                    %------------------------------------------------------
                    EFE(i) = spm_softmax(E)'*E;

                end

            end % end search over plausible states

            % accumulate expected free energy marginalised over states
            %--------------------------------------------------------------
            G(k) = G(k) + sum(EFE.*q,'all');

        end % end search over plausible states

    end % end search over actions


end


function [Q,P,qa,qb,F] = spm_backwards(O,P,Q,D,E,pa,pb,U,m,id)
% Backwards smoothing to evaluate posterior over initial states
%--------------------------------------------------------------------------
% O{m,g,t} - cell array of outcome probabilities for modality g
% P{m,k,t} - cell array of posteriors over paths
% Q{m,f,t} - cell array of posteriors over states
% D{m,f}   - cell array of priors over initial states
% E{m,k}   - belief propagators (action dependent probability transitions)
% pa{m,g}  - likelihood tensor  (Dirichlet parameters)
% pb{m,f}  - belief propagators (Dirichlet parameters)
% U{f}   - controllable factors
% m      - agent or model
%
% F      - Negative free energy (states, paths and parameters) ELBO
%
%  This subroutine performs Bayesian smoothing in the sense of a replay
%  using variational iterations to optimise posteriors over states, paths
%  and parameters, given the outcomes over an epoch. It effectively
%  implements the prior constraint that certain random variables (i.e., the
%  paths of uncontrollable factors and parameters) do not change with time
%__________________________________________________________________________

%  (iterative) variational scheme
%==========================================================================
tr    = @(A) pagetranspose(A);
T     = size(Q,3);
Nf    = size(Q,2);

% variational iterations
%--------------------------------------------------------------------------
Z     = -Inf;
for v = 1:16

    % initialise posterior Dirichlet parameters
    %----------------------------------------------------------------------
    F    = zeros(1,T);                   % variational free energy (ELBO)
    qa   = pa;
    qb   = pb;

    % acccumulate posterior Dirichlet parameters
    %======================================================================
    for t = 1:T

        % likelihood mapping from hidden states to outcomes: a
        %------------------------------------------------------------------
        ig    = spm_get_g(id{m},t);        % attended modalities
        for g = ig
            [j,i]   = spm_get_edges(id{m},g,Q(m,:,t));
            for o = i
                qa{m,g} = qa{m,g} + spm_cross(O{m,o,t},Q{m,j,t});
            end
            qa{m,g} = qa{m,g}.*(pa{m,g} > 0);
        end

        % mapping from hidden states to hidden states: b(u)
        %------------------------------------------------------------------
        if t < T
            for f = 1:numel(qb)
                qb{m,f} = qb{m,f} + spm_cross(spm_cross(Q{m,f,t + 1},Q{m,f,t}),P{m,f,t});
                qb{m,f} = qb{m,f}.*(pb{m,f} > 0);
            end
        end

    end

    % inference (Bayesian filtering)
    %======================================================================
    for t = 1:T

        if isfield(id{m},'independent')

            %  conditionally independent factors
            %--------------------------------------------------------------
            L      = cell(1,Nf);
            [L{:}] = deal(0);
            ig     = spm_get_g(id{m},t);              % attended modalities

            for g = ig
                [j,k] = spm_get_edges(id{m},g,Q(m,:,t));
                j     = unique(j,'stable');
                LL    = 0;
                for o = k
                    LL = LL + spm_log(spm_dot(spm_norm(qa{m,g}),O{m,o,t}));
                    %  = LL + spm_dot(spm_psi(qa{m,g}),O{m,o,t});
                end
                L{j} = L{j} + LL;
            end

            % posterior over hidden states
            %--------------------------------------------------------------
            for i = 1:Nf

                % log prior: smoothing
                %----------------------------------------------------------
                LP   = 0;
                if t == 1
                    LP = LP + spm_log(D{m,f});
                end
                if t < T
                    LP = LP + spm_dot(spm_psi(tr(qb{f})),P(m,f,t))*Q{m,f,t + 1};
                end
                if t > 1
                    LP = LP + spm_dot(spm_psi(qb{f}),P(m,f,t - 1))*Q{m,f,t - 1};
                end

                % posterior
                %----------------------------------------------------------
                Q{m,f,t} = spm_softmax(L{f} + LP);

                % ELBO free energy of states (accuracy and complexity)
                %----------------------------------------------------------
                F(t)     = F(t) + Q{m,f,t}'*(L{f} + LP - spm_log(Q{m,f,t}));

            end

        else

            %  conditionally dependent factors
            %--------------------------------------------------------------
        L     = 0;
        ig    = spm_get_g(id{m},t);         % attended modalities
        for g = ig
            [j,k] = spm_get_edges(id{m},g,Q(m,:,t));
            j  = unique(j,'stable');
            LL    = 0;
            for o = k
                LL = LL + spm_log(spm_dot(spm_norm(qa{m,g}),O{m,o,t}));
                %  = LL + spm_dot(spm_psi(qa{m,g}),O{m,o,t});
            end
            if numel(j) > 1
                [j,i] = sort(j);
                LL    = permute(LL,i);
            end
            k  = ones(1,Nf + 1); k(j) = size(LL,1:numel(j));
            L  = plus(L, reshape(LL,k));
        end

        % factors to update
            %--------------------------------------------------------------
            i = size(L);
            r = find(i > 1);
        L = reshape(L,[i(r) 1 1]);

        % only one latent state
            %--------------------------------------------------------------
        if isempty(r), F(t) = L; end
        
        % posterior over hidden states
            %--------------------------------------------------------------
        for i = 1:numel(r)

            % log likelihood
                %----------------------------------------------------------
            f    = r(i);
            LL   = spm_vec(spm_dot(L,Q(m,r,t),i));

            % log prior: smoothing
                %----------------------------------------------------------
            LP   = 0;
            if t == 1
                LP = LP + spm_log(D{m,f});
            end
            if t < T
                LP = LP + spm_dot(spm_psi(tr(qb{f})),P(m,f,t))*Q{m,f,t + 1};
            end
            if t > 1
                LP = LP + spm_dot(spm_psi(qb{f}),P(m,f,t - 1))*Q{m,f,t - 1};
            end

            % posterior
                %----------------------------------------------------------
            Q{m,f,t} = spm_softmax(LL + LP);

            % ELBO free energy of states (accuracy and complexity)
                %----------------------------------------------------------
            F(t)  = F(t) + Q{m,f,t}'*(LL + LP - spm_log(Q{m,f,t}));

        end
        end

    end

    % beliefs about paths
    %======================================================================
    for f = 1:numel(qb)

        % beliefs about (changing) paths
        %------------------------------------------------------------------
        if U{m}(f)

            for t = 2:T

                % log likelihood of control states
                %----------------------------------------------------------
                LL = spm_dot(spm_dot(spm_psi(qb{f}),Q{m,f,t}),Q{m,f,t - 1});

                % prior over control state
                %----------------------------------------------------------
                LP = spm_log(P{m,f,t - 1});

                % posterior over control states
                %----------------------------------------------------------
                P{m,f,t - 1} = spm_softmax(LL + LP);

                % ELBO free energy of paths (complexity)
                %----------------------------------------------------------
                F(t)  = F(t) + P{m,f,t - 1}'*(LL + LP - spm_log(P{m,f,t - 1}));

            end

        else  % beliefs about (unchanging) paths

            % accumulate log likelihood
            %--------------------------------------------------------------
            LL    = 0;
            for t = 2:T
                LL = LL + spm_dot(spm_dot(spm_psi(qb{f}),Q{m,f,t}),Q{m,f,t - 1});
            end

            % prior over control state
            %--------------------------------------------------------------
            LP = spm_log(E{m,f});

            % posterior over control states
            %--------------------------------------------------------------
            PP    = spm_softmax(LL + LP);
            for t = 1:T
                P{m,f,t} = PP;
            end

            % ELBO free energy of paths (complexity)
            %--------------------------------------------------------------
            F(t)  = F(t) + PP'*(LL + LP - spm_log(PP));

        end
    end

    % convergence
    %======================================================================
    dF = sum(F) - Z;

    % checks on ELBO
    %------------------------------------------------------------------------
    if sum(F) > 0
        warning('positive ELBO in spm_backwards')
    end
    if dF < 1/128
        break
    else
        Z = sum(F);
    end

end


return

function [R,hif] = spm_induction(A,B,C,H,Q,N,id)
% Inductive inference about next state
% FORMAT [R,hif] = spm_induction(A,B,C,H,Q,N,id)
%--------------------------------------------------------------------------
% A{1,g}   - likelihood mappings from hidden states
% B{1,f,k} - belief propagators (policy-dependent probability transitions)
% C{1,g}   - priors over outcomes (cost or constraint)
% H{1,f}   - cell array of priors over final state
% Q{1,f}   - cell array of posteriors over states
%
% N      - induction depth
% id     - domain structure
% 
%   id.hid(Nf,Ni)  - indices of Ni intended  states
%   id.cid(Nf,Ni)  - indices of Ni suprising states
%
% R      - tensor encoding unconstrained states over hif factors
% hif    - factors of tensor
%
% This subroutine returns constraints on the next state based upon
% backwards induction of a simple sort; i.e., using backwards propagators
% to identify paths of least action using logical operators.
% 
% In addition, constraints can be specified in a small number of latent
% factors by supplying a matrix of constraints, where each column
% corresponds to a distinct constraint and the number of rows corresponds
% to the number of hidden factors. This constraint matrix contains the
% index of the costly state for each factor. If an index is zero, the
% constraint is taken to be independent of the corresponding factor;
% otherwise, this conditional factor has to have a high posterior over the
% next state, before the constraint is implemented.
%__________________________________________________________________________

% Preliminary checks (for no priors over end states)
%==========================================================================

% Convert marginals to indices and find factors
%--------------------------------------------------------------------------
if isfield(id,'hid')

    if isa(id.hid,'function_handle')

        % intended states (hid) in factors hif
        %------------------------------------------------------------------
        [hid,hif] = id.hid(Q);

    else
    hid   = id.hid;                           % intended states
    hif   = find(any(hid,2))';                % in hif factors
    end

else

    % intended state from marginals (H)
    %----------------------------------------------------------------------
    hid   = [];
    hif   = [];
for f = 1:numel(H)
        if numel(H{f})
            [~,s]  = max(H{f});
            hid(end + 1,1) = s;
            hif(1,end + 1) = f;
end
    end
end

% Deal with constraints
%--------------------------------------------------------------------------
if isfield(id,'cid')

    if isa(id.cid,'function_handle')

        % disallowed states (D) in factors hif
        %------------------------------------------------------------------
        [D,hif] = id.cid(Q);

    else

    cid   = id.cid;                           % contrained factors
    nid   = cid;                              % conditioning factors
    hif   = find(all(cid,2))';                % in hif factors
    nid(hif,:) = 0;

    % size of contrained factors
        %------------------------------------------------------------------
        Ns    = ones(1,numel(hif) + 1);
    for f = hif
        Ns(f) = size(B{f},1);
    end

    
    % constraint tensor over hid factors
        %------------------------------------------------------------------
    D     = true(Ns);                        % unconstrained states
    for i = 1:size(cid,2)

        % posterior of constraint violation
            %--------------------------------------------------------------
        q     = 1;
        for f = find(nid(:,i))'
            q = q*Q{f}(cid(f,i));
        end
        if q > (1 - 1/8)
            ind  = num2cell(cid(hif,i));
                j    = spm_sub2ind(Ns,ind{:});
            D(j) = false;
        end
    end

    end
else
    D = true;
end

% Return if there are no intended states or constraints
%--------------------------------------------------------------------------
if isempty(hif), R = [];   return, end
if isempty(hid), R = 32*D;  return, end

% Threshold transition probabilities
%--------------------------------------------------------------------------
u     = 1/16;                         % probability threshold
for f = hif
    b{f}  = false;
    for k = 1:size(B,3)
        b{f} = b{f} | (B{1,f,k} > u);
    end
end

% Kronecker tensor products (sparse)
%--------------------------------------------------------------------------
Bf    = 1;
Qf    = 1;
for f = hif
    Ns(f) = size(B{f},1);                % number of states for hif
    Bf = spm_kron(b{f},Bf);           % unconstrained transitions
    Qf = spm_kron(Q{f},Qf);           % posterior over states
end

% Expected cost in latent state space
%==========================================================================
if numel(hif) == size(B,2)

    % Evaluate the cost of each hidden state
    %----------------------------------------------------------------------
% U = U + shiftdim(K{g},1);           % expected ambiguity (disabled)
Ns    = [Ns,1];                       % size of state space
L     = zeros(Ns);
for g = 1:numel(A)
    j = id.A{g};
    U = spm_dot(A{g},spm_log(C{g}));  % expected cost
    k = ones(1,numel(Ns)); k(j) = size(U,1:numel(j));
    L = plus(L, reshape(U,k));        % likely states
end

% Constraint from C
    %----------------------------------------------------------------------
L     = spm_vec(L);
L     = L > (max(L) + log(u));
    L     = L(:) & D(:);
else
    L     = D(:);
end
Bf    = and(Bf,L);                        % constrained transitions


% Backwards induction: from end states
%==========================================================================

% hid are indices (of multiple endpoints)
%--------------------------------------------------------------------------
for i = 1:size(hid,2)
    for f = hif
        h{f}    = false(Ns(f),1);
        h{f}(hid(f,i)) = true;
    end
        I     = true;
    for f = hif
            I = spm_kron(h{f},I);
        end
        Pf(:,i) = logical(I);
end


% Backwards induction: paths of least action
%==========================================================================
for i = 1:size(hid,2)

    % for this end state
    %----------------------------------------------------------------------
    I = logical(Pf(:,i));

    % backwards protocol (for paths with a well-defined end state)
    %----------------------------------------------------------------------
    for n = 1:min(N,64)

        % any preceding states % & that have not been previously occupied
        %------------------------------------------------------------------
        I(:,n + 1) = any(Bf(I(:,n),:),1)'; % & ~any(I,2);
end

    % Find most likely point on paths of least action
    %----------------------------------------------------------------------
    G(:,i) = I'*Qf;
    P{i}   = I;

end

% graphics for visualisation
%----------------------------------------------------------------------
if false
    spm_figure('GetWin','Inductive inference');
    for i = 1:min(size(hid,2),8)
        subplot(4,4,i)
        imagesc(P{i})
    end
    subplot(2,1,2)
    imagesc(G), axis square, drawnow
end

% precise log prior over next state
%==========================================================================
G(1,:) = 0;                        % preclude current states
[d,n]  = max(G,[],1);              % next intended state
i     = d > u;                     % provided it exists
if any(i)

    % eliminate inaccessible end states
    %----------------------------------------------------------------------
    P     = P(i);
    n     = n(i);
    [n,i] = min(n);                % to the i-th end state

    % precise log prior over next state
    %----------------------------------------------------------------------
    P     = P{i}(:,max(n - 1,1));
    R     = reshape(full(P),[Ns,1]);
    R     = 32*and(R,D);

else
    R     = [];
end

return

function g  = spm_get_g(id,t)             
% list of outcome modalities
% id.g      -  Indices of selected output modalities 
%--------------------------------------------------------------------------
if isfield(id,'g')
    if isfield(id,'ig')
        g = id.g{id.ig(t)};
    else
        g = unique(spm_vec(id.g));
    end
else
    g = 1:numel(id.A);
end

% ensure g is a row vector
%--------------------------------------------------------------------------
g = g(:)';


function i  = spm_is_process(MDP)
% invoke explicit action (process specified)
%----------------------------------------------------------------------
i = all(isfield(MDP,{'GA','GB','GU'}));

function i  = spm_sample(P)
% log of numeric array plus a small constant
%--------------------------------------------------------------------------
if islogical(P)
    i = find(P);
    i = i(randperm(numel(i),1));
else
    i = find(rand < cumsum(P),1);
end

function A  = spm_log(A)
% log of numeric array plus a small constant
%--------------------------------------------------------------------------
A           = max(log(A),-32);

function A  = spm_norm(A)
% normalisation of a probability transition matrix (columns)
%--------------------------------------------------------------------------
if isnumeric(A)
A           = rdivide(A,sum(A,1));
A(isnan(A)) = 1/size(A,1);
end

function A  = spm_wnorm(A)
% expected information gain (parameters)
% A = minus(log(A0),log(A)) + minus(1./A,1./A0) + minus(psi(A),psi(A0))
%   = minus(1./A,1./A0)/2 + ...
%--------------------------------------------------------------------------
A   = full(max(A,1/32));
if min(max(A),[],'all') < 256
A0  = sum(A);
A   = minus(log(A0),log(A)) + minus(1./A,1./A0) + minus(psi(A),psi(A0));
A   = max(A,0);
else
    A   = [];
end

function A  = spm_hnorm(A)
% expected conditional entropy (ambiguity)
%--------------------------------------------------------------------------
A     = spm_norm(A);
A     = full(sum(A.*spm_log(A),1));
if ~any(A,'all')
    A = [];
end

% Dirichlet entropies
%--------------------------------------------------------------------------
% A   = max(A,exp(-16));
% A0  = sum(A);
% K   = size(A,1);
% A   = spm_betaln(A) + (A0 - K).*psi(A0) - sum((A - 1).*psi(A));
% A   = min(A,0);

return


function [M,MDP] = spm_MDP_get_M(MDP,T,Ng)
% FORMAT [M,MDP] = spm_MDP_get_M(MDP,T,Ng)
% returns an update matrix for multiple models
% MDP(m) - structure array of m MPDs
% T      - number of trials or updates
% Ng(m)  - number of output modalities for m-th MDP
%
% M      - update matrix for multiple models
% MDP(m) - structure array of m MPDs
%
% In some applications, the outcomes are generated by a particular model
% (to maximise free energy, based upon the posterior predictive density).
% The generating model is specified in the matrix MDP(m).n, with a row for
% each outcome modality, such that each row lists the index of the model
% responsible for generating outcomes.
%__________________________________________________________________________

for m = 1:size(MDP,1)

    % check size of outcome generating agent, as specified by MDP(m).n
    %----------------------------------------------------------------------
    if ~isfield(MDP(m),'n')
        MDP(m).n = zeros(Ng(m),T);
    elseif isempty(MDP(m).n)
        MDP(m).n = zeros(Ng(m),T);
    end
    if size(MDP(m).n,1) < Ng(m)
        MDP(m).n = repmat(MDP(m).n(1,:),Ng(m),1);
    end
    if size(MDP(m).n,2) < T
        MDP(m).n = repmat(MDP(m).n(:,1),1,T);
    end

    % mode of generating model (most frequent over outcome modalities)
    %----------------------------------------------------------------------
    n(m,:) = mode(MDP(m).n.*(MDP(m).n > 0),1);

end

% reorder list of model indices for each update
%--------------------------------------------------------------------------
n     = mode(n,1);
for t = 1:T
    if n(t) > 0
        M(t,:) = circshift((1:size(MDP,1)),[0 (1 - n(t))]);
    else
        M(t,:) = 1:size(MDP,1);
    end
end


return

function MDP = spm_MDP_update(MDP,OUT)
% FORMAT MDP = spm_MDP_update(MDP,OUT)
% moves Dirichlet parameters from OUT to MDP
% MDP - structure array (new)
% OUT - structure array (old)
%__________________________________________________________________________

% check for concentration parameters at this level
%--------------------------------------------------------------------------
try,  MDP.a = OUT.a; end
try,  MDP.b = OUT.b; end
try,  MDP.c = OUT.c; end
try,  MDP.d = OUT.d; end
try,  MDP.e = OUT.e; end

% check for concentration parameters at nested levels
%--------------------------------------------------------------------------
try,  MDP.MDP(1).a = OUT.mdp(end).a; end
try,  MDP.MDP(1).b = OUT.mdp(end).b; end
try,  MDP.MDP(1).c = OUT.mdp(end).c; end
try,  MDP.MDP(1).d = OUT.mdp(end).d; end
try,  MDP.MDP(1).e = OUT.mdp(end).e; end

return

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


function r = spm_gamrnd(h,l)
% samples from a gamma distribution
% FORMAT r = spm_gamrnd(h,lambda)
% h - shape parameter
% l - scale parameter
%
% generates a random number from the gamma distribution with the shape
% parameter h and the scale paramemeter l.
%
% e.g.: r = spm_gamrnd(1,2)
% r = 
%     7.1297
%
% see also: spm_Gpdf(x,h,l)
%__________________________________________________________________________

U = rand(10000,h);
r = sum(-log(U),2)/l;

return

function r = spm_drchrnd(a,n)
% samples from a Dirichlet distribution
% FORMAT r = spm_drchrnd(a,n)
% a - Dirichlet paramters
% l - scale parameter
%
% e.g.: A = spm_drchrnd([1 1 1 1], 3)
% 
% A =
% 
% 0.3889 0.1738 0.0866 0.3507
% 0.0130 0.0874 0.6416 0.2579
% 0.0251 0.0105 0.2716 0.6928
%__________________________________________________________________________

p = length(a);
r = spm_gamrnd(repmat(a,n,1),1,n,p);
r = r ./ repmat(sum(r,2),1,p);

return

%% routines that call spm_MDP_VB_XXX
%--------------------------------------------------------------------------
% Routine:                   Demonstrating
%--------------------------------------------------------------------------
DEMO_MDP_maze_X             % Sophisticated inference
DEMO_MDP_maze_XXX           % Inductive inference
DEM_demo_MDP_XXX            % Active inference with backwards pass
DEM_Pong                    % Inductive inference and dynamics
DEM_Tower_of_Hanoi          % Active inference and structure learning
DEM_Tower                   % Inductive inference and problem solving
DEM_dSprites                % Structure learning with dynamics
DEM_sharingX                % Active selection with hyperlinks (id.A{g})
DEM_surveillance            % Factorial problem
DEM_drone                   % State-dependent likehood domains
DEM_drone_vision            % State-dependent likehood domains
DEM_drone_telemetry         % functional forms for likehood and domains
DEM_MNIST_conv              % Active sampling and state-dependent codomains

DEM_Atari                   % Conditionally independent factors
DEM_Atari_learning          % Conditionally independent factors
DEM_compression             % RGM for movies (simple)
DEM_video_compression       % RGM for movies (with learning)
DEM_sound_compression       % RGM for WAV files
DEM_music_compression       % RGM for WAV files
DEM_image_compression       % RGM for MNIST


DEM_MNIST                   % Active selection without dynamics
DEM_MNIST_mixture           % RGM for mixture of MNIST experts (MDPs)

