function [o] = spm_get_outcomes(MDP,m,f)
% Gets sequences generated by (generlised) states of an MDP
% FORMAT [o] = spm_get_outcomes(MDP,m,f)
% MDP  - Generative models (hierarchical)
% n    - level     [default: numel(MDP)]
% f    - factor[s] [default: 1]
%
% o    - logical vector over outcomes
%
%--------------------------------------------------------------------------
% This auxiliary routine traces the edges of a renormalising generative
% model from the factor f at level m to identify the children at the lowest
% level. In other words, it returns a logical vector o, over output
% modalities, if they are generated by the factor in question. By
% construction, these outputs form a (nonoverlapping) partition.
%__________________________________________________________________________

% defaults
%--------------------------------------------------------------------------
if nargin < 2, m = numel(MDP);              end
if nargin < 3, f = 1:size(MDP{end}.b{1},1); end

% get chidren recursively
%==========================================================================
for n = flip(2:m)

    % get children of factor
    %----------------------------------------------------------------------
    c = find(ismember([MDP{n}.id.A{:}],f));

    % get children of modality
    %----------------------------------------------------------------------
    f     = [];
    for g = c
        for d = 1:numel(MDP{n - 1}.id.D)
            if any(ismember(MDP{n - 1}.id.D{d},g))
                f(end + 1) = d;
            end
        end
    end
end

% final outcomes
%--------------------------------------------------------------------------
o    = false(numel(MDP{1}.id.A),1);
c    = ismember([MDP{1}.id.A{:}],f);
o(c) = true;

return
