function [O,p] = spm_get_sequences(MDP,Nm)
% Gets sequences generated by (generlised) states of an MDP
% FORMAT [O,o] = spm_get_sequences(MDP,Nm)
% MDP  - Generative models (hierarchical)
% Nm   - level [default: numel(MDP)]
%
% O    - O{Ns}{Ng,Nt}(No,1): cell array of probabilitic outcomes
% o    - o{Ns}(Ng,Nt): cell array of indexed outcomes
%
%--------------------------------------------------------------------------
% This auxiliary routine identifies the episodes (i.e., paths) encoded by
% states at the deepest or highest level of a hierarchical MDP.
%__________________________________________________________________________

% if nargin < 2, n = numel(MDP); end
%--------------------------------------------------------------------------
if nargin < 2, Nm = numel(MDP); end

% generate an episode encoded by the (i-th) state of the highest level
%==========================================================================
p     = {};
O     = {};
s     = cell(Nm,1);
Ni    = size(MDP{Nm}.b{1},1);
for i = 1:Ni
    s{Nm} = i;
    for n = flip(2:Nm)
        s{n - 1} = [];
        Nt    = size(s{n},2);
        for t = 1:Nt

            % generate level n outcomes
            %--------------------------------------------------------------
            Ng    = numel(MDP{n}.id.A);
            o     = zeros(Ng,1);
            for g = 1:Ng
                
                if n == Nm

                    % generate from first stream
                    %------------------------------------------------------
                    j    = MDP{n}.id.A{g};
                    if j == 1
                        [~,j]  = max(MDP{n}.a{g}(:,s{n}(j,t)));
                        o(g) = j;
                    end

                else

                    % within stream generation
                    %------------------------------------------------------
                    j     = MDP{n}.id.A{g};
                    [~,j] = max(MDP{n}.a{g}(:,s{n}(j,t)));
                    o(g)  = j;

                end
            end

            % ensuing paths at level n - 1
            %--------------------------------------------------------------
            Ns    = numel(MDP{n - 1}.id.D);
            x     = zeros(Ns,MDP{n}.T);
            for f = 1:Ns
                if n == Nm

                    % generate from first stream
                    %------------------------------------------------------
                    gx = MDP{n - 1}.id.D{f}(end);
                    gu = MDP{n - 1}.id.E{f}(end);

                else

                    % within stream generation
                    %------------------------------------------------------
                    gx = MDP{n - 1}.id.D{f}(1);
                    gu = MDP{n - 1}.id.E{f}(1);

                end

                % generalised states
                %----------------------------------------------------------
                if numel(gx)
                    x(f,1) = o(gx);
                else
                    x(f,1) = 1;
                end
                if numel(gu)
                    u = o(gu);
                else
                    u = 1;
                end

                % iterate over time under generated path
                %----------------------------------------------------------
                for r  = 2:MDP{n}.T
                    [~,j]  = max(MDP{n - 1}.b{f}(:,x(f,r - 1),u));
                    x(f,r) = j;
                end

            end
            s{n - 1} = [s{n - 1} x];
        end
    end

    % final outcomes
    %----------------------------------------------------------------------
    for t = 1:size(s{1},2)
        Ng    = numel(MDP{1}.id.A);
        for g = 1:Ng
            j     = MDP{1}.id.A{g};
            po    = MDP{1}.a{g}(:,s{1}(j,t));
            [~,j] = max(po);

            p{i}(g,t) = j;
            O{i}{g,t} = spm_dir_norm(po);
        end
    end

end

return
