function spm_DEM_EEG(DEM,dt)
% simulated electrophysiological response based on conditional estimates
% FORMAT spm_DEM_EEG(DEM,dt)
% DEM - DEM structure
% dt  - time bib (seconds)
% R   - response over peri-stimulus time (whitened error)
%
% These simulated response assume that LFPs are generated by superficial
% pyramidal cells that correspond to units [whitened] encoding prediction 
% error.
%
% see also spm_DEM_ERP
%__________________________________________________________________________
% Copyright (C) 2008 Wellcome Trust Centre for Neuroimaging
 
% Karl Friston
% $Id: spm_DEM_EEG.m 1380 2008-04-11 18:55:18Z karl $
 
% defaults
%--------------------------------------------------------------------------
try
    dt;
catch
    try
        dt = DEM.U.dt;
    catch
        dt = 1;
    end
end
 
% loop over hierarchical (cortical) levels
%--------------------------------------------------------------------------
cla
hold on
U     = DEM.qU.z;
pst   = [1:size(U{1},2)]*dt*1000;
n     = length(U);
for i = 1:n
 
    % precisions
    %----------------------------------------------------------------------
    P   = DEM.M(i).V;
    for j = 1:length(DEM.qH.h{i})
        P = P + DEM.M(1).Q{j}*DEM.qH.h{i}(j);
    end
    
    % ERPs
    %----------------------------------------------------------------------
    R   = P*U{i};
    plot(pst,R,'Color',[3/4 1/4 1/4]/i,'LineWidth',2)
 
end
 
% labels
%--------------------------------------------------------------------------
xlabel('peristimulus time (ms)')
ylabel('LFP (micro-volts)')
grid on
hold off
drawnow
