function [HID,CID,HITS,MISS,O] = spm_get_episodes(hid,cid,GDP,MDP)
% Gets rewarded (and restricted) states at the deepest level of an MDP
% FORMAT [HID,CID,HITS,MISS,O] = spm_get_episodes(hid,cid,GDP,MDP)
% hid  - List of intended (i.e., rewarded) goal states at the lowest level
% cid  - List of constrained (i.e., restricted) states at the lowest level
% GDP  - Generative process
% MDP  - Generative models (hierarchical)
%
% HID  - List of intended (i.e., rewarded) goal states at highest level
% CID  - List of constrained (i.e., restricted) states at highest level
% HITS - List of intended (i.e. rewarded) goal outcomes at lowest level
% MISS - List of constrained (i.e. restricted) outcomes at lowest level
%
% O    - Cell array of outcome probabilities for each episode
%
%--------------------------------------------------------------------------
% This auxiliary routine identifies the episodes (i.e., paths) encoded by
% states at the deepest or highest level of a hierarchical MDP that entail
% one or more intended states at the lowest level.
%
% It also generates outcome probabilities as episodes at the lowest level
% (that are shared with the generative process)
%__________________________________________________________________________

% Find outcomes generated by rewarded and restricted states
%--------------------------------------------------------------------------
Ng    = numel(GDP.A);
Nh    = size(hid,2);
Nc    = size(cid,2);
HITS  = zeros(Ng,Nh);
MISS  = zeros(Ng,Nh);
for g = 1:Ng
    for h = 1:Nh
        ind       = num2cell(hid(:,h));
        HITS(g,h) = find(GDP.A{g}(:,ind{:}),1);
    end
    for h = 1:Nc
        ind       = num2cell(cid(:,h));
        MISS(g,h) = find(GDP.A{g}(:,ind{:}),1);
    end
end

% Solve for an episode encoded by the (i-th) state of the highest level
%--------------------------------------------------------------------------
T     = 2;
O     = {};
HID   = [];
CID   = [];
Nm    = numel(MDP);
Ni    = size(MDP{Nm}.B{1},1);
for i = 1:Ni
    s{Nm} = i;
    for n = flip(2:Nm)
        s{n - 1} = [];
        for t = 1:size(s{n},2)

            % generate level n outcomes 
            %--------------------------------------------------------------
            No    = numel(MDP{n}.id.A);
            for g = 1:No
                j       = MDP{n}.id.A{g};
                o{n}(g,t) = find(MDP{n}.A{g}(:,s{n}(j,t)));
            end

            % ensuing paths at level n - 1
            %--------------------------------------------------------------
            Ns    = numel(MDP{n - 1}.id.D);
            x     = zeros(Ns,T);
            for f = 1:Ns
                x(f,1) = o{n}(MDP{n - 1}.id.D{f},t);
                u      = o{n}(MDP{n - 1}.id.E{f},t);
                for r = 2:T
                    x(f,r) = find(MDP{n - 1}.B{f}(:,x(f,r - 1),u),1);
                end

            end
            s{n - 1} = [s{n - 1} x];
        end
    end

    % final outcomes
    %----------------------------------------------------------------------
    n     = 1;
    for t = 1:size(s{n},2)
        No    = numel(MDP{n}.id.A);
        for g = 1:No
            j         = MDP{n}.id.A{g};
            O{i}{g,t} = MDP{n}.A{g}(:,s{n}(j,t));
            o{n}(g,t) = find(O{i}{g,t},1);
        end
    end

    % does this episode elcit a reward?
    %----------------------------------------------------------------------
    if any(ismember(o{1}',HITS','rows'))
        HID = [HID,i];
    end
    if any(ismember(o{1}',MISS','rows'))
        CID = [CID,i];
    end

end

return

% Convert hierarchical MDP to recursive RDP
%--------------------------------------------------------------------------
% RDP       = spm_mdp2rdp(MDP);
% [~,Ns,Nu] = spm_MDP_size(RDP);
% 
% % Solve for an episode encoded by the states of the highest level
% %--------------------------------------------------------------------------
% RDP.T = 1;
% HID   = [];
% CID   = [];
% for s = 1:Ns(1)
% 
%     RDP.D{1} = sparse(s,1,1,Ns(1),1);
%     RDP.E{1} = sparse(1,1,1,Nu(1),1);
%     PDP      = spm_MDP_VB_XXX(RDP);
% 
%     % does this path elcit a reward?
%     %----------------------------------------------------------------------
%     o       = PDP.Q.o{1};
%     if sum(ismember(o',HITS','rows'))
%         HID = [HID,s];
%     end
%     if sum(ismember(o',MISS','rows'))
%         CID = [CID,s];
%     end
% 
% end


