function [R] = spm_DEM_EEG(DEM,dt)
% simulated electrophysiological response based on conditional estimates
% FORMAT [R] = spm_DEM_EEG(DEM,dt)
% DEM  - DEM structure
% dt   - time bin (seconds)
% R{i} - response over peri-stimulus time (whitened error): level i
%
% These simulated response assume that LFPs are generated by superficial
% pyramidal cells that correspond to units encoding precision-weighted 
% prediction error.
%
% see also spm_DEM_ERP
%__________________________________________________________________________
% Copyright (C) 2008 Wellcome Trust Centre for Neuroimaging
 
% Karl Friston
% $Id: spm_DEM_EEG.m 2710 2009-02-06 19:57:40Z karl $
 
% defaults
%--------------------------------------------------------------------------
try
    dt;
catch
    try
        dt = DEM.U.dt;
    catch
        dt = 1;
    end
end
 
% loop over hierarchical (cortical) levels
%--------------------------------------------------------------------------
cla
hold on
z     = DEM.qU.z;
pst   = [1:size(z{1},2)]*dt*1000;
n     = length(z);
for i = 1:n
 
    % precisions
    %----------------------------------------------------------------------
    P   = DEM.M(i).V;
    for j = 1:length(DEM.qH.h{i})
        P = P + DEM.M(i).Q{j}*DEM.qH.h{i}(j);
    end
    
    % ERPs
    %----------------------------------------------------------------------
    R{i}  = P*z{i};
    if i == 1
        plot(pst,R{i},'r:')
    else
        plot(pst,R{i},'r')
    end
 
end
 
% labels
%--------------------------------------------------------------------------
xlabel('peristimulus time (ms)')
ylabel('LFP (micro-volts)')
box on
hold off
drawnow
