function [HID,CID,HITS,MISS] = spm_get_episodes(hid,cid,GDP,MDP)
% Gets rewarded (and restricted) states at the deepest level of an MDP
% FORMAT [HID,CID,HITS,MISS] = spm_get_episodes(hid,cid,GDP,MDP)
% hid  - List of intended (i.e., rewarded) goal states at the lowest level
% cid  - List of constrained (i.e., restricted) states at the lowest level
% GDP  - Generative process
% MDP  - Generative models (hierarchical)
%
% HID  - List of intended (i.e., rewarded) goal states at highest level
% CID  - List of constrained (i.e., restricted) states at highest level
% HITS - List of intended (i.e. rewarded) goal outcomes at lowest level
% MISS - List of constrained (i.e. restricted) outcomes at lowest level
%
%--------------------------------------------------------------------------
% This auxiliary routine identifies the episodes (i.e., paths) encoded by
% states at the deepest or highest level of a hierarchical MDP that entail
% one or more intended states at the lowest level.
%
% It also generates outcome probabilities as episodes at the lowest level
% (that are shared with the generative process)
%__________________________________________________________________________

% Find outcomes generated by rewarded and restricted states
%--------------------------------------------------------------------------
Ng    = numel(GDP.A);
Nh    = size(hid,2);
Nc    = size(cid,2);
HITS  = zeros(Ng,Nh);
MISS  = zeros(Ng,Nh);
for g = 1:Ng
    for h = 1:Nh
        ind       = num2cell(hid(:,h));
        [~,j]     = max(GDP.A{g}(:,ind{:}));
        HITS(g,h) = j;
    end
    for h = 1:Nc
        ind       = num2cell(cid(:,h));
        [~,j]     = max(GDP.A{g}(:,ind{:}));
        MISS(g,h) = j;
    end
end

% Solve for an episode encoded by the (i-th) state of the highest level
%--------------------------------------------------------------------------
HID   = [];
CID   = [];
O     = spm_get_sequences(MDP);
Ni    = numel(O);
for i = 1:Ni
 
    % final outcomes
    %----------------------------------------------------------------------
    o     = zeros(size(O{i}));
    for t = 1:size(o,2)
        for g = 1:size(o,1)
            [~,j]  = max(O{i}{g,t});
            o(g,t) = j;
        end
    end

    % does this episode elcit a reward?
    %----------------------------------------------------------------------
    if any(ismember(o',HITS','rows'))
        HID = [HID,i];
    end
    if any(ismember(o',MISS','rows'))
        CID = [CID,i];
    end

end

return

% NOTES for full version
%__________________________________________________________________________

% Convert hierarchical MDP to recursive RDP
%--------------------------------------------------------------------------
% RDP       = spm_mdp2rdp(MDP);
% [~,Ns,Nu] = spm_MDP_size(RDP);
% 
% % Solve for an episode encoded by the states of the highest level
% %------------------------------------------------------------------------
% RDP.T = 1;
% HID   = [];
% CID   = [];
% for s = 1:Ns(1)
% 
%     RDP.D{1} = sparse(s,1,1,Ns(1),1);
%     RDP.E{1} = sparse(1,1,1,Nu(1),1);
%     PDP      = spm_MDP_VB_XXX(RDP);
% 
%     % does this path elcit a reward?
%     %--------------------------------------------------------------------
%     o       = PDP.Q.o{1};
%     if sum(ismember(o',HITS','rows'))
%         HID = [HID,s];
%     end
%     if sum(ismember(o',MISS','rows'))
%         CID = [CID,s];
%     end
% 
% end


