function out = spm_run_normalise_estwrite(varargin)
% SPM job execution function
% takes a harvested job data structure and call SPM functions to perform
% computations on the data.
% Input:
% job    - harvested job data structure (see matlabbatch help)
% Output:
% out    - computation results, usually a struct variable.
%_______________________________________________________________________
% Copyright (C) 2008 Wellcome Trust Centre for Neuroimaging

% $Id: spm_run_normalise_estwrite.m 2312 2008-10-07 17:02:46Z volkmar $

job    = varargin{1};
o      = job.eoptions;
eflags = struct(...
    'smosrc', o.smosrc,...
    'smoref', o.smoref,...
    'regtype',o.regtype,...
    'cutoff', o.cutoff,...
    'nits',   o.nits,...
    'reg',    o.reg);
o      = job.roptions;
rflags = struct(...
    'preserve',o.preserve,...
    'bb',      o.bb,...
    'vox',     o.vox,...
    'interp',  o.interp,...
    'wrap',    o.wrap,...
        'prefix',  o.prefix);

for i=1:numel(job.subj),
    [ pth,nam ] = spm_fileparts(deblank(job.subj(i).source{:}));
    out(i).params{1}  = fullfile(pth,[nam,'_sn.mat']);
    spm_normalise(strvcat(job.eoptions.template{:}),...
        strvcat(job.subj(i).source{:}), out(i).params{1},...
        strvcat(job.eoptions.weight), strvcat(job.subj(i).wtsrc), eflags);
    spm_write_sn(strvcat(job.subj(i).resample{:}), out(i).params{1}, rflags);
    out(i).files = cell(size(job.subj(i).resample));
    for j=1:numel(job.subj(i).resample),
        [pth,nam,ext,num] = spm_fileparts(job.subj(i).resample{j});
        out(i).files{j}   = fullfile(pth,[job.roptions.prefix, nam, ext, num]);
    end;
end;
return;
