function ecat = spm_cfg_ecat
% SPM Configuration file
% automatically generated by the MATLABBATCH utility function GENCODE
%_______________________________________________________________________
% Copyright (C) 2008 Wellcome Trust Centre for Neuroimaging

% $Id: spm_cfg_ecat.m 1295 2008-04-02 14:31:24Z volkmar $

rev = '$Rev: 1295 $';
% ---------------------------------------------------------------------
% data ECAT files
% ---------------------------------------------------------------------
data         = cfg_files;
data.tag     = 'data';
data.name    = 'ECAT files';
data.help    = {'Select the ECAT files to convert.'};
data.filter = 'any';
data.ufilter = '.*v';
data.num     = [1 Inf];
% ---------------------------------------------------------------------
% ext NIFTI Type
% ---------------------------------------------------------------------
ext         = cfg_menu;
ext.tag     = 'ext';
ext.name    = 'NIFTI Type';
ext.val = {'.img'};
ext.help    = {'Output files can be written as .img + .hdr, or the two can be combined into a .nii file.'};
ext.labels = {
              '.nii only'
              '.img + .hdr'
}';
ext.values = {
              '.nii'
              '.img'
}';
% ---------------------------------------------------------------------
% opts Options
% ---------------------------------------------------------------------
opts         = cfg_branch;
opts.tag     = 'opts';
opts.name    = 'Options';
opts.val     = {ext };
opts.help    = {'Conversion options'};
% ---------------------------------------------------------------------
% ecat ECAT Import
% ---------------------------------------------------------------------
ecat         = cfg_exbranch;
ecat.tag     = 'ecat';
ecat.name    = 'ECAT Import';
ecat.val     = {data opts };
ecat.help    = {'ECAT 7 Conversion.  ECAT 7 is the image data format used by the more recent CTI PET scanners.'};
ecat.prog = @convert_ecat;
ecat.modality = {'PET'};
%------------------------------------------------------------------------

%------------------------------------------------------------------------
function convert_ecat(job)
for i=1:length(job.data),
    spm_ecat2nifti(job.data{i},job.opts);
end;
return;
