function runbatch = spm_cfg_runbatch
% SPM Configuration file
% automatically generated by the MATLABBATCH utility function GENCODE
%_______________________________________________________________________
% Copyright (C) 2008 Wellcome Trust Centre for Neuroimaging

% $Id: spm_cfg_runbatch.m 1292 2008-04-02 14:17:31Z volkmar $

rev = '$Rev';
% ---------------------------------------------------------------------
% jobs Batch Files
% ---------------------------------------------------------------------
jobs         = cfg_files;
jobs.tag     = 'jobs';
jobs.name    = 'Batch Files';
jobs.help    = {'Select the batch job files to be run.'};
jobs.filter = 'batch';
jobs.ufilter = '.*';
jobs.num     = [1 Inf];
% ---------------------------------------------------------------------
% runbatch Execute Batch Jobs
% ---------------------------------------------------------------------
runbatch         = cfg_exbranch;
runbatch.tag     = 'runbatch';
runbatch.name    = 'Execute Batch Jobs';
runbatch.val     = {jobs };
runbatch.help    = {'This facility allows previously created batch jobs to be run. These are simply created by the batch user interface (which you are currently using).'};
% can't run this in matlabbatch
runbatch.prog = @false;
