% SPM Configuration file
% automatically generated by the MATLABBATCH utility function GENCODE
%_______________________________________________________________________
% Copyright (C) 2008 Wellcome Trust Centre for Neuroimaging

% $Id: spm_cfg_cat.m 1185 2008-03-04 16:31:21Z volkmar $

rev = '$Rev$';
