function ui = spm_cfg_ui
% SPM Configuration file
% automatically generated by the MATLABBATCH utility function GENCODE
%_______________________________________________________________________
% Copyright (C) 2008 Wellcome Trust Centre for Neuroimaging

% $Id: spm_cfg_ui.m 1295 2008-04-02 14:31:24Z volkmar $

rev = '$Rev: 1295 $';
% ---------------------------------------------------------------------
% colour1 Background Colour 1
% ---------------------------------------------------------------------
colour1         = cfg_entry;
colour1.tag     = 'colour1';
colour1.name    = 'Background Colour 1';
colour1.val{1} = double([0.800000000000000044 0.800000000000000044 1]);
colour1.help    = {''};
colour1.strtype = 'e';
colour1.num     = [1 3];
colour1.extras = double([0 1]);
% ---------------------------------------------------------------------
% colour2 Background Colour 2
% ---------------------------------------------------------------------
colour2         = cfg_entry;
colour2.tag     = 'colour2';
colour2.name    = 'Background Colour 2';
colour2.val{1} = double([1 1 0.800000000000000044]);
colour2.help    = {''};
colour2.strtype = 'e';
colour2.num     = [1 3];
colour2.extras = double([0 1]);
% ---------------------------------------------------------------------
% colour3 Foreground Colour
% ---------------------------------------------------------------------
colour3         = cfg_entry;
colour3.tag     = 'colour3';
colour3.name    = 'Foreground Colour';
colour3.val{1} = double([0 0 0]);
colour3.help    = {''};
colour3.strtype = 'e';
colour3.num     = [1 3];
colour3.extras = double([0 1]);
% ---------------------------------------------------------------------
% fs Font Size
% ---------------------------------------------------------------------
fs         = cfg_menu;
fs.tag     = 'fs';
fs.name    = 'Font Size';
fs.val{1} = double(14);
fs.help    = {''};
fs.labels = {
             '8'
             '9'
             '10'
             '12'
             '14'
             '16'
             '18'
}';
fs.values{1} = double(8);
fs.values{2} = double(9);
fs.values{3} = double(10);
fs.values{4} = double(12);
fs.values{5} = double(14);
fs.values{6} = double(16);
fs.values{7} = double(18);
% ---------------------------------------------------------------------
% appearance Appearance
% ---------------------------------------------------------------------
appearance         = cfg_branch;
appearance.tag     = 'appearance';
appearance.name    = 'Appearance';
appearance.val     = {colour1 colour2 colour3 fs };
appearance.help    = {'Appearance of user interface'};
% ---------------------------------------------------------------------
% print Printing
% ---------------------------------------------------------------------
print         = cfg_menu;
print.tag     = 'print';
print.name    = 'Printing';
print.val{1}.opt = {
                    '-dpsc2'
                    '-append'
}';
print.val{1}.append = logical(true);
print.val{1}.ext = '.ps';
print.help    = {'Select the printing option you want.  The figure will be printed to a file named spm5*.*, in the current directory.  PostScript files will be appended to, but other files will have "page numbers" appended to them.'};
print.labels = {
                'PostScript for black and white printers'
                'PostScript for colour printers'
                'Level 2 PostScript for black and white printers'
                'Level 2 PostScript for colour printers'
                'Encapsulated PostScript (EPSF)'
                'Encapsulated Colour PostScript (EPSF)'
                'Encapsulated Level 2 PostScript (EPSF)'
                'Encapsulated Level 2 Color PostScript (EPSF)'
                'Encapsulated                with TIFF preview'
                'Encapsulated Colour         with TIFF preview'
                'Encapsulated Level 2        with TIFF preview'
                'Encapsulated Level 2 Colour with TIFF preview'
                'HPGL compatible with Hewlett-Packard 7475A plotter'
                'Adobe Illustrator 88 compatible illustration file'
                'M-file (and Mat-file, if necessary)'
                'Baseline JPEG image'
                'TIFF with packbits compression'
                'Color image format'
}';
print.values{1}.opt = {
                       '-dps'
                       '-append'
}';
print.values{1}.append = logical(true);
print.values{1}.ext = '.ps';
print.values{2}.opt = {
                       '-dpsc'
                       '-append'
}';
print.values{2}.append = logical(true);
print.values{2}.ext = '.ps';
print.values{3}.opt = {
                       '-dps2'
                       '-append'
}';
print.values{3}.append = logical(true);
print.values{3}.ext = '.ps';
print.values{4}.opt = {
                       '-dpsc2'
                       '-append'
}';
print.values{4}.append = logical(true);
print.values{4}.ext = '.ps';
print.values{5}.opt = {'-deps'};
print.values{5}.append = logical(false);
print.values{5}.ext = '.eps';
print.values{6}.opt = {'-depsc'};
print.values{6}.append = logical(false);
print.values{6}.ext = '.eps';
print.values{7}.opt = {'-deps2'};
print.values{7}.append = logical(false);
print.values{7}.ext = '.eps';
print.values{8}.opt = {'-depsc2'};
print.values{8}.append = logical(false);
print.values{8}.ext = '.eps';
print.values{9}.opt = {
                       '-deps'
                       '-tiff'
}';
print.values{9}.append = logical(false);
print.values{9}.ext = '.eps';
print.values{10}.opt = {
                        '-depsc'
                        '-tiff'
}';
print.values{10}.append = logical(false);
print.values{10}.ext = '.eps';
print.values{11}.opt = {
                        '-deps2'
                        '-tiff'
}';
print.values{11}.append = logical(false);
print.values{11}.ext = '.eps';
print.values{12}.opt = {
                        '-depsc2'
                        '-tiff'
}';
print.values{12}.append = logical(false);
print.values{12}.ext = '.eps';
print.values{13}.opt = {'-dhpgl'};
print.values{13}.append = logical(false);
print.values{13}.ext = '.hpgl';
print.values{14}.opt = {'-dill'};
print.values{14}.append = logical(false);
print.values{14}.ext = '.ill';
print.values{15}.opt = {'-dmfile'};
print.values{15}.append = logical(false);
print.values{15}.ext = '.m';
print.values{16}.opt = {'-djpeg'};
print.values{16}.append = logical(false);
print.values{16}.ext = '.jpg';
print.values{17}.opt = {'-dtiff'};
print.values{17}.append = logical(false);
print.values{17}.ext = '.tif';
print.values{18}.opt = {'-dtiffnocompression'};
print.values{18}.append = logical(false);
print.values{18}.ext = '.tif';
% ---------------------------------------------------------------------
% ui User Interface
% ---------------------------------------------------------------------
ui         = cfg_branch;
ui.tag     = 'ui';
ui.name    = 'User Interface';
ui.val     = {appearance print };
ui.help    = {''};
