% SPM Configuration file
% automatically generated by the MATLABBATCH utility function GENCODE
%__________________________________________________________________________

% Copyright (C) 2005-2022 Wellcome Centre for Human Neuroimaging

