function md = spm_cfg_md
% SPM Configuration file
% automatically generated by the MATLABBATCH utility function GENCODE
%_______________________________________________________________________
% Copyright (C) 2008 Wellcome Trust Centre for Neuroimaging

% $Id: spm_cfg_md.m 1292 2008-04-02 14:17:31Z volkmar $

rev = '$Rev';
% ---------------------------------------------------------------------
% basedir Select a base directory
% ---------------------------------------------------------------------
basedir         = cfg_files;
basedir.tag     = 'basedir';
basedir.name    = 'Select a base directory';
basedir.help    = {'Select a base directory.'};
basedir.filter = 'dir';
basedir.ufilter = '.*';
basedir.num     = [1 1];
% ---------------------------------------------------------------------
% name Enter a directory name
% ---------------------------------------------------------------------
name         = cfg_entry;
name.tag     = 'name';
name.name    = 'Enter a directory name';
name.help    = {'Enter a directory name'};
name.strtype = 's';
name.num     = [1 Inf];
% ---------------------------------------------------------------------
% md Make Directory (Deprecated)
% ---------------------------------------------------------------------
md         = cfg_exbranch;
md.tag     = 'md';
md.name    = 'Make Directory (Deprecated)';
md.val     = {basedir name };
md.help    = {
              'This module is deprecated and has been moved to BasicIO.'
              'Jobs which are ready to run may continue using it, but the module inputs can not be changed via GUI. Please switch to the BasicIO module instead.'
              'This facilty allows programming a directory change. Directories are selected in the right listbox.'
}';
md.prog = @my_mkdir;
md.vfiles = @vdirs_mydirs;
md.hidden = true;
%------------------------------------------------------------------------

%------------------------------------------------------------------------
function my_mkdir(varargin)
job = varargin{1};
if ~isempty(job.basedir) && ~isempty(job.name)
    mkdir(job.basedir{:},job.name);
end
%------------------------------------------------------------------------

%------------------------------------------------------------------------

function vd = vdirs_mydirs(varargin)

job = varargin{1};

vd = {fullfile(job.basedir{:},[job.name,filesep])};
return;

