function spm_DipoleFit
% Provides the interface for the "dipole fitting" toolbox
% 
% There are 3 steps for EEG dipole fitting: 1. build head model 
% (volumes & electrode location), 2. define how dipoles should be 
% fitting and find them, 3. display results. For each of these 
% steps, the GUI offers options/sub-steps. I've also added the 
% possibility to display a few interesting(?) bits.
% 
% 1) Head model. The head model is build from an image (sMRI, fMRI
%   or EPI). The image is segmented to obtain the brain volume and 
%   the surface is tesselated (for a sMRI image, the scalp surface 
%   is also extracted) [spm_eegfp_model.m]. Electrodes are then 
%   added to the model. Their location/name can be user defined or
%   be a standard system [spm_eegfp_electrset.m]. 
%   Finally spheres are adjuste don the head model in order to use 
%   a "realistic sphere approach" to solve the forward problem 
%   analytically while keeping some anatomical information 
%   [spm_eegfp_Rsph.m].
% 
% 2) Dipole fitting. The GUI routine [spm_eegip_fitDip_gui.m] asks
%   all the questions and checks the inputs (model and data), then
%   calls the fitting routine itself [spm_eegip_fitDip.m]. The 
%   cost function optimised is defined in spm_eegip_costSd.m
% 
% 3) Results. The fitted dipoles can be displayed on an image 
%   [spm_eegip_DrawDip.m]. If multiple random seeds have been used, 
%   the "similar" solution can be collapsed into a single one which
%   renders things easier to interprete [spm_eegip_sDipRes.m].
% 
% 4) Draw/display. It is possible to display the tesselated surfaces
%   with or without electrodes [spm_eeg_displTes.m, 
%   spm_eeg_displScEl.m]. The data and adjusted data can also be 
%   interpolated and displayed on a plane disk [spm_eeg_DrawSV.m,
%   spm_eegip_fittedEEG.m].
% 
% The routines can also be called from the command line or with a script. This will offer a few  
% more "hidden" options...
% Things still to be done:
% - make it compatible with MEG data
% - allow more options for the dipole fitting. Eg. a mix of fixed and moving sources, symmetric 
% sources.
%_______________________________________________________________________
% Copyright (C) 2005 Wellcome Department of Imaging Neuroscience

% Christophe Phillips,
% $Id$

SPMid = spm('FnBanner',mfilename,'1.2');
[Finter,Fgraph,CmdLine] = spm('FnUIsetup','Dipole Fitting');
spm_help('!ContextHelp',mfilename);

fig = spm_figure('GetWin','Interactive');
h0  = uimenu(fig,...
	'Label',	'Dipole Fitting',...
	'Separator',	'on',...
	'Tag',		'Def',...
	'HandleVisibility','on');
h1  = uimenu(h0,...
	'Label',	'Create Head Model',...
	'Separator',	'off',...
	'Tag',		'Def',...
	'HandleVisibility','on');
h2  = uimenu(h1,...
	'Label',	'Generate binarised volume and Tesselate',...
	'Separator',	'off',...
	'Tag',		'Def',...
	'CallBack',	'spm_eegfp_model(''init'',1);',...
	'HandleVisibility','on');
h2  = uimenu(h1,...
	'Label',	'Tesselate binarised volume only',...
	'Separator',	'off',...
	'Tag',		'Def',...
	'CallBack',	'spm_eegfp_model(''init'',2);',...
	'HandleVisibility','on');
h2  = uimenu(h1,...
	'Label',	'Add electrodes to the model',...
	'Separator',	'off',...
	'Tag',		'Def',...
	'CallBack',	'spm_eegfp_model(''init'',3);',...
	'HandleVisibility','on');
h2  = uimenu(h1,...
	'Label',	'Build realistic sphere model',...
	'Separator',	'off',...
	'Tag',		'Def',...
	'CallBack',	'spm_eegfp_model(''init'',4);',...
	'HandleVisibility','on');
h2  = uimenu(h1,...
	'Label',	'Do all this at once',...
	'Separator',	'off',...
	'Tag',		'Def',...
	'CallBack',	'spm_eegfp_model(''init'',5);',...
	'HandleVisibility','on');
h1  = uimenu(h0,...
	'Label',	'Fit dipoles',...
	'Separator',	'on',...
	'Tag',		'Def',...
	'CallBack',	'spm_eegip_fitDip_gui;',...
	'HandleVisibility','on');
h1  = uimenu(h0,...
	'Label',	'Results of dipole fitting',...
	'Separator',	'on',...
	'Tag',		'Def',...
	'HandleVisibility','on');
h2  = uimenu(h1,...
	'Label',	'Display dipoles on image',...
	'Separator',	'off',...
	'Tag',		'Def',...
	'CallBack',	'spm_eegip_DrawDip(''Init'');',...
	'HandleVisibility','on');
h2  = uimenu(h1,...
	'Label',	'Summarize results and Display',...
	'Separator',	'off',...
	'Tag',		'Def',...
	'CallBack',	'spm_eegip_sDipRes;',...
	'HandleVisibility','on');
h1  = uimenu(h0,...
	'Label',	'Draw...',...
	'Separator',	'on',...
	'Tag',		'Def',...
	'HandleVisibility','on');
h2  = uimenu(h1,...
	'Label',	'Tesselated surface',...
	'Separator',	'off',...
	'Tag',		'Def',...
	'CallBack',	'spm_eeg_displTes;',...
	'HandleVisibility','on');
h2  = uimenu(h1,...
	'Label',	'Tesselated surface with electrodes',...
	'Separator',	'off',...
	'Tag',		'Def',...
	'CallBack',	'spm_eeg_displScEl;',...
	'HandleVisibility','on');
h2  = uimenu(h1,...
	'Label',	'Mapped EEG on scalp',...
	'Separator',	'off',...
	'Tag',		'Def',...
	'CallBack',	'spm_eeg_DrawSV;',...
	'HandleVisibility','on');
h2  = uimenu(h1,...
	'Label',	'Mapped fitted EEG on scalp',...
	'Separator',	'off',...
	'Tag',		'Def',...
	'CallBack',	'spm_eegip_fittedEEG;',...
	'HandleVisibility','on');
